// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ApplicationUpdateV2Reader is a Reader for the ApplicationUpdateV2 structure.
type ApplicationUpdateV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationUpdateV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewApplicationUpdateV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewApplicationUpdateV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewApplicationUpdateV2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationUpdateV2OK creates a ApplicationUpdateV2OK with default headers values
func NewApplicationUpdateV2OK() *ApplicationUpdateV2OK {
	return &ApplicationUpdateV2OK{}
}

/*ApplicationUpdateV2OK handles this case with default header values.

Ok
*/
type ApplicationUpdateV2OK struct {
	Payload *models.UpdateDocumentResponse
}

func (o *ApplicationUpdateV2OK) Error() string {
	return fmt.Sprintf("[PUT /application/{id}][%d] applicationUpdateV2OK  %+v", 200, o.Payload)
}

func (o *ApplicationUpdateV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationUpdateV2BadRequest creates a ApplicationUpdateV2BadRequest with default headers values
func NewApplicationUpdateV2BadRequest() *ApplicationUpdateV2BadRequest {
	return &ApplicationUpdateV2BadRequest{}
}

/*ApplicationUpdateV2BadRequest handles this case with default header values.

Bad request
*/
type ApplicationUpdateV2BadRequest struct {
}

func (o *ApplicationUpdateV2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /application/{id}][%d] applicationUpdateV2BadRequest ", 400)
}

func (o *ApplicationUpdateV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplicationUpdateV2Default creates a ApplicationUpdateV2Default with default headers values
func NewApplicationUpdateV2Default(code int) *ApplicationUpdateV2Default {
	return &ApplicationUpdateV2Default{
		_statusCode: code,
	}
}

/*ApplicationUpdateV2Default handles this case with default header values.

Unexpected error
*/
type ApplicationUpdateV2Default struct {
	_statusCode int
}

// Code gets the status code for the application update v2 default response
func (o *ApplicationUpdateV2Default) Code() int {
	return o._statusCode
}

func (o *ApplicationUpdateV2Default) Error() string {
	return fmt.Sprintf("[PUT /application/{id}][%d] ApplicationUpdateV2 default ", o._statusCode)
}

func (o *ApplicationUpdateV2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
