// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// CategoryGetReader is a Reader for the CategoryGet structure.
type CategoryGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CategoryGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCategoryGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCategoryGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCategoryGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCategoryGetOK creates a CategoryGetOK with default headers values
func NewCategoryGetOK() *CategoryGetOK {
	return &CategoryGetOK{}
}

/*CategoryGetOK handles this case with default header values.

Ok
*/
type CategoryGetOK struct {
	Payload *models.Category
}

func (o *CategoryGetOK) Error() string {
	return fmt.Sprintf("[GET /categories/{id}][%d] categoryGetOK  %+v", 200, o.Payload)
}

func (o *CategoryGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Category)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCategoryGetBadRequest creates a CategoryGetBadRequest with default headers values
func NewCategoryGetBadRequest() *CategoryGetBadRequest {
	return &CategoryGetBadRequest{}
}

/*CategoryGetBadRequest handles this case with default header values.

Bad request
*/
type CategoryGetBadRequest struct {
}

func (o *CategoryGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /categories/{id}][%d] categoryGetBadRequest ", 400)
}

func (o *CategoryGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCategoryGetDefault creates a CategoryGetDefault with default headers values
func NewCategoryGetDefault(code int) *CategoryGetDefault {
	return &CategoryGetDefault{
		_statusCode: code,
	}
}

/*CategoryGetDefault handles this case with default header values.

Unexpected error
*/
type CategoryGetDefault struct {
	_statusCode int
}

// Code gets the status code for the category get default response
func (o *CategoryGetDefault) Code() int {
	return o._statusCode
}

func (o *CategoryGetDefault) Error() string {
	return fmt.Sprintf("[GET /categories/{id}][%d] CategoryGet default ", o._statusCode)
}

func (o *CategoryGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
