// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// CategoryCreateReader is a Reader for the CategoryCreate structure.
type CategoryCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CategoryCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCategoryCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCategoryCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCategoryCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCategoryCreateOK creates a CategoryCreateOK with default headers values
func NewCategoryCreateOK() *CategoryCreateOK {
	return &CategoryCreateOK{}
}

/*CategoryCreateOK handles this case with default header values.

Ok
*/
type CategoryCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *CategoryCreateOK) Error() string {
	return fmt.Sprintf("[POST /categories][%d] categoryCreateOK  %+v", 200, o.Payload)
}

func (o *CategoryCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCategoryCreateBadRequest creates a CategoryCreateBadRequest with default headers values
func NewCategoryCreateBadRequest() *CategoryCreateBadRequest {
	return &CategoryCreateBadRequest{}
}

/*CategoryCreateBadRequest handles this case with default header values.

Bad request
*/
type CategoryCreateBadRequest struct {
}

func (o *CategoryCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /categories][%d] categoryCreateBadRequest ", 400)
}

func (o *CategoryCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCategoryCreateDefault creates a CategoryCreateDefault with default headers values
func NewCategoryCreateDefault(code int) *CategoryCreateDefault {
	return &CategoryCreateDefault{
		_statusCode: code,
	}
}

/*CategoryCreateDefault handles this case with default header values.

Unexpected error
*/
type CategoryCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the category create default response
func (o *CategoryCreateDefault) Code() int {
	return o._statusCode
}

func (o *CategoryCreateDefault) Error() string {
	return fmt.Sprintf("[POST /categories][%d] CategoryCreate default ", o._statusCode)
}

func (o *CategoryCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
