// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// CertificatesCreateReader is a Reader for the CertificatesCreate structure.
type CertificatesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CertificatesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCertificatesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCertificatesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCertificatesCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCertificatesCreateOK creates a CertificatesCreateOK with default headers values
func NewCertificatesCreateOK() *CertificatesCreateOK {
	return &CertificatesCreateOK{}
}

/*CertificatesCreateOK handles this case with default header values.

Certificates
*/
type CertificatesCreateOK struct {
	Payload *models.Certificates
}

func (o *CertificatesCreateOK) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] certificatesCreateOK  %+v", 200, o.Payload)
}

func (o *CertificatesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Certificates)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCertificatesCreateBadRequest creates a CertificatesCreateBadRequest with default headers values
func NewCertificatesCreateBadRequest() *CertificatesCreateBadRequest {
	return &CertificatesCreateBadRequest{}
}

/*CertificatesCreateBadRequest handles this case with default header values.

Bad request
*/
type CertificatesCreateBadRequest struct {
}

func (o *CertificatesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] certificatesCreateBadRequest ", 400)
}

func (o *CertificatesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCertificatesCreateDefault creates a CertificatesCreateDefault with default headers values
func NewCertificatesCreateDefault(code int) *CertificatesCreateDefault {
	return &CertificatesCreateDefault{
		_statusCode: code,
	}
}

/*CertificatesCreateDefault handles this case with default header values.

Unexpected error
*/
type CertificatesCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the certificates create default response
func (o *CertificatesCreateDefault) Code() int {
	return o._statusCode
}

func (o *CertificatesCreateDefault) Error() string {
	return fmt.Sprintf("[POST /certificates][%d] CertificatesCreate default ", o._statusCode)
}

func (o *CertificatesCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
