// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// CloudCredsDeleteReader is a Reader for the CloudCredsDelete structure.
type CloudCredsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CloudCredsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCloudCredsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCloudCredsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCloudCredsDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCloudCredsDeleteOK creates a CloudCredsDeleteOK with default headers values
func NewCloudCredsDeleteOK() *CloudCredsDeleteOK {
	return &CloudCredsDeleteOK{}
}

/*CloudCredsDeleteOK handles this case with default header values.

Ok
*/
type CloudCredsDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *CloudCredsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /cloudcreds/{id}][%d] cloudCredsDeleteOK  %+v", 200, o.Payload)
}

func (o *CloudCredsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudCredsDeleteBadRequest creates a CloudCredsDeleteBadRequest with default headers values
func NewCloudCredsDeleteBadRequest() *CloudCredsDeleteBadRequest {
	return &CloudCredsDeleteBadRequest{}
}

/*CloudCredsDeleteBadRequest handles this case with default header values.

Bad request
*/
type CloudCredsDeleteBadRequest struct {
}

func (o *CloudCredsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /cloudcreds/{id}][%d] cloudCredsDeleteBadRequest ", 400)
}

func (o *CloudCredsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCloudCredsDeleteDefault creates a CloudCredsDeleteDefault with default headers values
func NewCloudCredsDeleteDefault(code int) *CloudCredsDeleteDefault {
	return &CloudCredsDeleteDefault{
		_statusCode: code,
	}
}

/*CloudCredsDeleteDefault handles this case with default header values.

Unexpected error
*/
type CloudCredsDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the cloud creds delete default response
func (o *CloudCredsDeleteDefault) Code() int {
	return o._statusCode
}

func (o *CloudCredsDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /cloudcreds/{id}][%d] CloudCredsDelete default ", o._statusCode)
}

func (o *CloudCredsDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
