// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ContainerRegistryListReader is a Reader for the ContainerRegistryList structure.
type ContainerRegistryListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerRegistryListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContainerRegistryListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewContainerRegistryListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewContainerRegistryListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewContainerRegistryListOK creates a ContainerRegistryListOK with default headers values
func NewContainerRegistryListOK() *ContainerRegistryListOK {
	return &ContainerRegistryListOK{}
}

/*ContainerRegistryListOK handles this case with default header values.

Ok
*/
type ContainerRegistryListOK struct {
	Payload []*models.ContainerRegistry
}

func (o *ContainerRegistryListOK) Error() string {
	return fmt.Sprintf("[GET /containerregistries][%d] containerRegistryListOK  %+v", 200, o.Payload)
}

func (o *ContainerRegistryListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerRegistryListBadRequest creates a ContainerRegistryListBadRequest with default headers values
func NewContainerRegistryListBadRequest() *ContainerRegistryListBadRequest {
	return &ContainerRegistryListBadRequest{}
}

/*ContainerRegistryListBadRequest handles this case with default header values.

Bad request
*/
type ContainerRegistryListBadRequest struct {
}

func (o *ContainerRegistryListBadRequest) Error() string {
	return fmt.Sprintf("[GET /containerregistries][%d] containerRegistryListBadRequest ", 400)
}

func (o *ContainerRegistryListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerRegistryListDefault creates a ContainerRegistryListDefault with default headers values
func NewContainerRegistryListDefault(code int) *ContainerRegistryListDefault {
	return &ContainerRegistryListDefault{
		_statusCode: code,
	}
}

/*ContainerRegistryListDefault handles this case with default header values.

Unexpected error
*/
type ContainerRegistryListDefault struct {
	_statusCode int
}

// Code gets the status code for the container registry list default response
func (o *ContainerRegistryListDefault) Code() int {
	return o._statusCode
}

func (o *ContainerRegistryListDefault) Error() string {
	return fmt.Sprintf("[GET /containerregistries][%d] ContainerRegistryList default ", o._statusCode)
}

func (o *ContainerRegistryListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
