// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataStreamListParams creates a new DataStreamListParams object
// with the default values initialized.
func NewDataStreamListParams() *DataStreamListParams {
	var ()
	return &DataStreamListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataStreamListParamsWithTimeout creates a new DataStreamListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataStreamListParamsWithTimeout(timeout time.Duration) *DataStreamListParams {
	var ()
	return &DataStreamListParams{

		timeout: timeout,
	}
}

// NewDataStreamListParamsWithContext creates a new DataStreamListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataStreamListParamsWithContext(ctx context.Context) *DataStreamListParams {
	var ()
	return &DataStreamListParams{

		Context: ctx,
	}
}

// NewDataStreamListParamsWithHTTPClient creates a new DataStreamListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataStreamListParamsWithHTTPClient(client *http.Client) *DataStreamListParams {
	var ()
	return &DataStreamListParams{
		HTTPClient: client,
	}
}

/*DataStreamListParams contains all the parameters to send to the API endpoint
for the data stream list operation typically these are written to a http.Request
*/
type DataStreamListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data stream list params
func (o *DataStreamListParams) WithTimeout(timeout time.Duration) *DataStreamListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data stream list params
func (o *DataStreamListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data stream list params
func (o *DataStreamListParams) WithContext(ctx context.Context) *DataStreamListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data stream list params
func (o *DataStreamListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data stream list params
func (o *DataStreamListParams) WithHTTPClient(client *http.Client) *DataStreamListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data stream list params
func (o *DataStreamListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the data stream list params
func (o *DataStreamListParams) WithAuthorization(authorization string) *DataStreamListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the data stream list params
func (o *DataStreamListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *DataStreamListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
