// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// DataSourceCreateReader is a Reader for the DataSourceCreate structure.
type DataSourceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DataSourceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDataSourceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDataSourceCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDataSourceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDataSourceCreateOK creates a DataSourceCreateOK with default headers values
func NewDataSourceCreateOK() *DataSourceCreateOK {
	return &DataSourceCreateOK{}
}

/*DataSourceCreateOK handles this case with default header values.

Ok
*/
type DataSourceCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *DataSourceCreateOK) Error() string {
	return fmt.Sprintf("[POST /datasources][%d] dataSourceCreateOK  %+v", 200, o.Payload)
}

func (o *DataSourceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDataSourceCreateBadRequest creates a DataSourceCreateBadRequest with default headers values
func NewDataSourceCreateBadRequest() *DataSourceCreateBadRequest {
	return &DataSourceCreateBadRequest{}
}

/*DataSourceCreateBadRequest handles this case with default header values.

Bad request
*/
type DataSourceCreateBadRequest struct {
}

func (o *DataSourceCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /datasources][%d] dataSourceCreateBadRequest ", 400)
}

func (o *DataSourceCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDataSourceCreateDefault creates a DataSourceCreateDefault with default headers values
func NewDataSourceCreateDefault(code int) *DataSourceCreateDefault {
	return &DataSourceCreateDefault{
		_statusCode: code,
	}
}

/*DataSourceCreateDefault handles this case with default header values.

Unexpected error
*/
type DataSourceCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the data source create default response
func (o *DataSourceCreateDefault) Code() int {
	return o._statusCode
}

func (o *DataSourceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /datasources][%d] DataSourceCreate default ", o._statusCode)
}

func (o *DataSourceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
