// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// DataSourceGetReader is a Reader for the DataSourceGet structure.
type DataSourceGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DataSourceGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDataSourceGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDataSourceGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDataSourceGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDataSourceGetOK creates a DataSourceGetOK with default headers values
func NewDataSourceGetOK() *DataSourceGetOK {
	return &DataSourceGetOK{}
}

/*DataSourceGetOK handles this case with default header values.

Ok
*/
type DataSourceGetOK struct {
	Payload *models.DataSource
}

func (o *DataSourceGetOK) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}][%d] dataSourceGetOK  %+v", 200, o.Payload)
}

func (o *DataSourceGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataSource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDataSourceGetBadRequest creates a DataSourceGetBadRequest with default headers values
func NewDataSourceGetBadRequest() *DataSourceGetBadRequest {
	return &DataSourceGetBadRequest{}
}

/*DataSourceGetBadRequest handles this case with default header values.

Bad request
*/
type DataSourceGetBadRequest struct {
}

func (o *DataSourceGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}][%d] dataSourceGetBadRequest ", 400)
}

func (o *DataSourceGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDataSourceGetDefault creates a DataSourceGetDefault with default headers values
func NewDataSourceGetDefault(code int) *DataSourceGetDefault {
	return &DataSourceGetDefault{
		_statusCode: code,
	}
}

/*DataSourceGetDefault handles this case with default header values.

Unexpected error
*/
type DataSourceGetDefault struct {
	_statusCode int
}

// Code gets the status code for the data source get default response
func (o *DataSourceGetDefault) Code() int {
	return o._statusCode
}

func (o *DataSourceGetDefault) Error() string {
	return fmt.Sprintf("[GET /datasources/{id}][%d] DataSourceGet default ", o._statusCode)
}

func (o *DataSourceGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
