// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// DockerProfileCreateReader is a Reader for the DockerProfileCreate structure.
type DockerProfileCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DockerProfileCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDockerProfileCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDockerProfileCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDockerProfileCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDockerProfileCreateOK creates a DockerProfileCreateOK with default headers values
func NewDockerProfileCreateOK() *DockerProfileCreateOK {
	return &DockerProfileCreateOK{}
}

/*DockerProfileCreateOK handles this case with default header values.

Ok
*/
type DockerProfileCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *DockerProfileCreateOK) Error() string {
	return fmt.Sprintf("[POST /dockerprofiles][%d] dockerProfileCreateOK  %+v", 200, o.Payload)
}

func (o *DockerProfileCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDockerProfileCreateBadRequest creates a DockerProfileCreateBadRequest with default headers values
func NewDockerProfileCreateBadRequest() *DockerProfileCreateBadRequest {
	return &DockerProfileCreateBadRequest{}
}

/*DockerProfileCreateBadRequest handles this case with default header values.

Bad request
*/
type DockerProfileCreateBadRequest struct {
}

func (o *DockerProfileCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /dockerprofiles][%d] dockerProfileCreateBadRequest ", 400)
}

func (o *DockerProfileCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDockerProfileCreateDefault creates a DockerProfileCreateDefault with default headers values
func NewDockerProfileCreateDefault(code int) *DockerProfileCreateDefault {
	return &DockerProfileCreateDefault{
		_statusCode: code,
	}
}

/*DockerProfileCreateDefault handles this case with default header values.

Unexpected error
*/
type DockerProfileCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the docker profile create default response
func (o *DockerProfileCreateDefault) Code() int {
	return o._statusCode
}

func (o *DockerProfileCreateDefault) Error() string {
	return fmt.Sprintf("[POST /dockerprofiles][%d] DockerProfileCreate default ", o._statusCode)
}

func (o *DockerProfileCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
