// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// EdgeGetReader is a Reader for the EdgeGet structure.
type EdgeGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeGetOK creates a EdgeGetOK with default headers values
func NewEdgeGetOK() *EdgeGetOK {
	return &EdgeGetOK{}
}

/*EdgeGetOK handles this case with default header values.

Ok
*/
type EdgeGetOK struct {
	Payload *models.Edge
}

func (o *EdgeGetOK) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}][%d] edgeGetOK  %+v", 200, o.Payload)
}

func (o *EdgeGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Edge)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeGetBadRequest creates a EdgeGetBadRequest with default headers values
func NewEdgeGetBadRequest() *EdgeGetBadRequest {
	return &EdgeGetBadRequest{}
}

/*EdgeGetBadRequest handles this case with default header values.

Bad request
*/
type EdgeGetBadRequest struct {
}

func (o *EdgeGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}][%d] edgeGetBadRequest ", 400)
}

func (o *EdgeGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeGetDefault creates a EdgeGetDefault with default headers values
func NewEdgeGetDefault(code int) *EdgeGetDefault {
	return &EdgeGetDefault{
		_statusCode: code,
	}
}

/*EdgeGetDefault handles this case with default header values.

Unexpected error
*/
type EdgeGetDefault struct {
	_statusCode int
}

// Code gets the status code for the edge get default response
func (o *EdgeGetDefault) Code() int {
	return o._statusCode
}

func (o *EdgeGetDefault) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}][%d] EdgeGet default ", o._statusCode)
}

func (o *EdgeGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
