// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// EdgeUpgradeListReader is a Reader for the EdgeUpgradeList structure.
type EdgeUpgradeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeUpgradeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeUpgradeListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeUpgradeListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeUpgradeListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeUpgradeListOK creates a EdgeUpgradeListOK with default headers values
func NewEdgeUpgradeListOK() *EdgeUpgradeListOK {
	return &EdgeUpgradeListOK{}
}

/*EdgeUpgradeListOK handles this case with default header values.

Ok
*/
type EdgeUpgradeListOK struct {
	Payload []*models.EdgeUpgradeCore
}

func (o *EdgeUpgradeListOK) Error() string {
	return fmt.Sprintf("[GET /edgesCompatibleUpgrades][%d] edgeUpgradeListOK  %+v", 200, o.Payload)
}

func (o *EdgeUpgradeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeUpgradeListBadRequest creates a EdgeUpgradeListBadRequest with default headers values
func NewEdgeUpgradeListBadRequest() *EdgeUpgradeListBadRequest {
	return &EdgeUpgradeListBadRequest{}
}

/*EdgeUpgradeListBadRequest handles this case with default header values.

Bad request
*/
type EdgeUpgradeListBadRequest struct {
}

func (o *EdgeUpgradeListBadRequest) Error() string {
	return fmt.Sprintf("[GET /edgesCompatibleUpgrades][%d] edgeUpgradeListBadRequest ", 400)
}

func (o *EdgeUpgradeListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeUpgradeListDefault creates a EdgeUpgradeListDefault with default headers values
func NewEdgeUpgradeListDefault(code int) *EdgeUpgradeListDefault {
	return &EdgeUpgradeListDefault{
		_statusCode: code,
	}
}

/*EdgeUpgradeListDefault handles this case with default header values.

Unexpected error
*/
type EdgeUpgradeListDefault struct {
	_statusCode int
}

// Code gets the status code for the edge upgrade list default response
func (o *EdgeUpgradeListDefault) Code() int {
	return o._statusCode
}

func (o *EdgeUpgradeListDefault) Error() string {
	return fmt.Sprintf("[GET /edgesCompatibleUpgrades][%d] EdgeUpgradeList default ", o._statusCode)
}

func (o *EdgeUpgradeListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
