// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// EdgeListReader is a Reader for the EdgeList structure.
type EdgeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeListOK creates a EdgeListOK with default headers values
func NewEdgeListOK() *EdgeListOK {
	return &EdgeListOK{}
}

/*EdgeListOK handles this case with default header values.

Ok
*/
type EdgeListOK struct {
	Payload []*models.Edge
}

func (o *EdgeListOK) Error() string {
	return fmt.Sprintf("[GET /edges][%d] edgeListOK  %+v", 200, o.Payload)
}

func (o *EdgeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeListBadRequest creates a EdgeListBadRequest with default headers values
func NewEdgeListBadRequest() *EdgeListBadRequest {
	return &EdgeListBadRequest{}
}

/*EdgeListBadRequest handles this case with default header values.

Bad request
*/
type EdgeListBadRequest struct {
}

func (o *EdgeListBadRequest) Error() string {
	return fmt.Sprintf("[GET /edges][%d] edgeListBadRequest ", 400)
}

func (o *EdgeListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeListDefault creates a EdgeListDefault with default headers values
func NewEdgeListDefault(code int) *EdgeListDefault {
	return &EdgeListDefault{
		_statusCode: code,
	}
}

/*EdgeListDefault handles this case with default header values.

Unexpected error
*/
type EdgeListDefault struct {
	_statusCode int
}

// Code gets the status code for the edge list default response
func (o *EdgeListDefault) Code() int {
	return o._statusCode
}

func (o *EdgeListDefault) Error() string {
	return fmt.Sprintf("[GET /edges][%d] EdgeList default ", o._statusCode)
}

func (o *EdgeListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
