// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// EdgeGetDatasourcesReader is a Reader for the EdgeGetDatasources structure.
type EdgeGetDatasourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeGetDatasourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeGetDatasourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeGetDatasourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeGetDatasourcesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeGetDatasourcesOK creates a EdgeGetDatasourcesOK with default headers values
func NewEdgeGetDatasourcesOK() *EdgeGetDatasourcesOK {
	return &EdgeGetDatasourcesOK{}
}

/*EdgeGetDatasourcesOK handles this case with default header values.

Ok
*/
type EdgeGetDatasourcesOK struct {
	Payload []*models.DataSource
}

func (o *EdgeGetDatasourcesOK) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/datasources][%d] edgeGetDatasourcesOK  %+v", 200, o.Payload)
}

func (o *EdgeGetDatasourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeGetDatasourcesBadRequest creates a EdgeGetDatasourcesBadRequest with default headers values
func NewEdgeGetDatasourcesBadRequest() *EdgeGetDatasourcesBadRequest {
	return &EdgeGetDatasourcesBadRequest{}
}

/*EdgeGetDatasourcesBadRequest handles this case with default header values.

Bad request
*/
type EdgeGetDatasourcesBadRequest struct {
}

func (o *EdgeGetDatasourcesBadRequest) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/datasources][%d] edgeGetDatasourcesBadRequest ", 400)
}

func (o *EdgeGetDatasourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeGetDatasourcesDefault creates a EdgeGetDatasourcesDefault with default headers values
func NewEdgeGetDatasourcesDefault(code int) *EdgeGetDatasourcesDefault {
	return &EdgeGetDatasourcesDefault{
		_statusCode: code,
	}
}

/*EdgeGetDatasourcesDefault handles this case with default header values.

Unexpected error
*/
type EdgeGetDatasourcesDefault struct {
	_statusCode int
}

// Code gets the status code for the edge get datasources default response
func (o *EdgeGetDatasourcesDefault) Code() int {
	return o._statusCode
}

func (o *EdgeGetDatasourcesDefault) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/datasources][%d] EdgeGetDatasources default ", o._statusCode)
}

func (o *EdgeGetDatasourcesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
