// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// EdgeGetSensorsReader is a Reader for the EdgeGetSensors structure.
type EdgeGetSensorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeGetSensorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeGetSensorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeGetSensorsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeGetSensorsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeGetSensorsOK creates a EdgeGetSensorsOK with default headers values
func NewEdgeGetSensorsOK() *EdgeGetSensorsOK {
	return &EdgeGetSensorsOK{}
}

/*EdgeGetSensorsOK handles this case with default header values.

Ok
*/
type EdgeGetSensorsOK struct {
	Payload []*models.Sensor
}

func (o *EdgeGetSensorsOK) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/sensors][%d] edgeGetSensorsOK  %+v", 200, o.Payload)
}

func (o *EdgeGetSensorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeGetSensorsBadRequest creates a EdgeGetSensorsBadRequest with default headers values
func NewEdgeGetSensorsBadRequest() *EdgeGetSensorsBadRequest {
	return &EdgeGetSensorsBadRequest{}
}

/*EdgeGetSensorsBadRequest handles this case with default header values.

Bad request
*/
type EdgeGetSensorsBadRequest struct {
}

func (o *EdgeGetSensorsBadRequest) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/sensors][%d] edgeGetSensorsBadRequest ", 400)
}

func (o *EdgeGetSensorsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeGetSensorsDefault creates a EdgeGetSensorsDefault with default headers values
func NewEdgeGetSensorsDefault(code int) *EdgeGetSensorsDefault {
	return &EdgeGetSensorsDefault{
		_statusCode: code,
	}
}

/*EdgeGetSensorsDefault handles this case with default header values.

Unexpected error
*/
type EdgeGetSensorsDefault struct {
	_statusCode int
}

// Code gets the status code for the edge get sensors default response
func (o *EdgeGetSensorsDefault) Code() int {
	return o._statusCode
}

func (o *EdgeGetSensorsDefault) Error() string {
	return fmt.Sprintf("[GET /edges/{edgeId}/sensors][%d] EdgeGetSensors default ", o._statusCode)
}

func (o *EdgeGetSensorsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
