// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// LogEntriesListReader is a Reader for the LogEntriesList structure.
type LogEntriesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogEntriesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLogEntriesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewLogEntriesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewLogEntriesListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLogEntriesListOK creates a LogEntriesListOK with default headers values
func NewLogEntriesListOK() *LogEntriesListOK {
	return &LogEntriesListOK{}
}

/*LogEntriesListOK handles this case with default header values.

Ok
*/
type LogEntriesListOK struct {
	Payload []*models.LogEntry
}

func (o *LogEntriesListOK) Error() string {
	return fmt.Sprintf("[GET /logs/entries][%d] logEntriesListOK  %+v", 200, o.Payload)
}

func (o *LogEntriesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogEntriesListBadRequest creates a LogEntriesListBadRequest with default headers values
func NewLogEntriesListBadRequest() *LogEntriesListBadRequest {
	return &LogEntriesListBadRequest{}
}

/*LogEntriesListBadRequest handles this case with default header values.

Bad request
*/
type LogEntriesListBadRequest struct {
}

func (o *LogEntriesListBadRequest) Error() string {
	return fmt.Sprintf("[GET /logs/entries][%d] logEntriesListBadRequest ", 400)
}

func (o *LogEntriesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLogEntriesListDefault creates a LogEntriesListDefault with default headers values
func NewLogEntriesListDefault(code int) *LogEntriesListDefault {
	return &LogEntriesListDefault{
		_statusCode: code,
	}
}

/*LogEntriesListDefault handles this case with default header values.

Unexpected error
*/
type LogEntriesListDefault struct {
	_statusCode int
}

// Code gets the status code for the log entries list default response
func (o *LogEntriesListDefault) Code() int {
	return o._statusCode
}

func (o *LogEntriesListDefault) Error() string {
	return fmt.Sprintf("[GET /logs/entries][%d] LogEntriesList default ", o._statusCode)
}

func (o *LogEntriesListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
