// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OAuthAuthorizeCallReader is a Reader for the OAuthAuthorizeCall structure.
type OAuthAuthorizeCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OAuthAuthorizeCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewOAuthAuthorizeCallBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewOAuthAuthorizeCallUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewOAuthAuthorizeCallDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOAuthAuthorizeCallBadRequest creates a OAuthAuthorizeCallBadRequest with default headers values
func NewOAuthAuthorizeCallBadRequest() *OAuthAuthorizeCallBadRequest {
	return &OAuthAuthorizeCallBadRequest{}
}

/*OAuthAuthorizeCallBadRequest handles this case with default header values.

Bad request
*/
type OAuthAuthorizeCallBadRequest struct {
}

func (o *OAuthAuthorizeCallBadRequest) Error() string {
	return fmt.Sprintf("[GET /oauth2/authorize][%d] oAuthAuthorizeCallBadRequest ", 400)
}

func (o *OAuthAuthorizeCallBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOAuthAuthorizeCallUnauthorized creates a OAuthAuthorizeCallUnauthorized with default headers values
func NewOAuthAuthorizeCallUnauthorized() *OAuthAuthorizeCallUnauthorized {
	return &OAuthAuthorizeCallUnauthorized{}
}

/*OAuthAuthorizeCallUnauthorized handles this case with default header values.

Login failed
*/
type OAuthAuthorizeCallUnauthorized struct {
}

func (o *OAuthAuthorizeCallUnauthorized) Error() string {
	return fmt.Sprintf("[GET /oauth2/authorize][%d] oAuthAuthorizeCallUnauthorized ", 401)
}

func (o *OAuthAuthorizeCallUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOAuthAuthorizeCallDefault creates a OAuthAuthorizeCallDefault with default headers values
func NewOAuthAuthorizeCallDefault(code int) *OAuthAuthorizeCallDefault {
	return &OAuthAuthorizeCallDefault{
		_statusCode: code,
	}
}

/*OAuthAuthorizeCallDefault handles this case with default header values.

Unexpected error
*/
type OAuthAuthorizeCallDefault struct {
	_statusCode int
}

// Code gets the status code for the o auth authorize call default response
func (o *OAuthAuthorizeCallDefault) Code() int {
	return o._statusCode
}

func (o *OAuthAuthorizeCallDefault) Error() string {
	return fmt.Sprintf("[GET /oauth2/authorize][%d] OAuthAuthorizeCall default ", o._statusCode)
}

func (o *OAuthAuthorizeCallDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
