// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ProjectListReader is a Reader for the ProjectList structure.
type ProjectListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectListOK creates a ProjectListOK with default headers values
func NewProjectListOK() *ProjectListOK {
	return &ProjectListOK{}
}

/*ProjectListOK handles this case with default header values.

Ok
*/
type ProjectListOK struct {
	Payload []*models.Project
}

func (o *ProjectListOK) Error() string {
	return fmt.Sprintf("[GET /projects][%d] projectListOK  %+v", 200, o.Payload)
}

func (o *ProjectListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectListBadRequest creates a ProjectListBadRequest with default headers values
func NewProjectListBadRequest() *ProjectListBadRequest {
	return &ProjectListBadRequest{}
}

/*ProjectListBadRequest handles this case with default header values.

Bad request
*/
type ProjectListBadRequest struct {
}

func (o *ProjectListBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects][%d] projectListBadRequest ", 400)
}

func (o *ProjectListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectListDefault creates a ProjectListDefault with default headers values
func NewProjectListDefault(code int) *ProjectListDefault {
	return &ProjectListDefault{
		_statusCode: code,
	}
}

/*ProjectListDefault handles this case with default header values.

Unexpected error
*/
type ProjectListDefault struct {
	_statusCode int
}

// Code gets the status code for the project list default response
func (o *ProjectListDefault) Code() int {
	return o._statusCode
}

func (o *ProjectListDefault) Error() string {
	return fmt.Sprintf("[GET /projects][%d] ProjectList default ", o._statusCode)
}

func (o *ProjectListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
