// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ProjectCreateReader is a Reader for the ProjectCreate structure.
type ProjectCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectCreateOK creates a ProjectCreateOK with default headers values
func NewProjectCreateOK() *ProjectCreateOK {
	return &ProjectCreateOK{}
}

/*ProjectCreateOK handles this case with default header values.

Ok
*/
type ProjectCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *ProjectCreateOK) Error() string {
	return fmt.Sprintf("[POST /projects][%d] projectCreateOK  %+v", 200, o.Payload)
}

func (o *ProjectCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectCreateBadRequest creates a ProjectCreateBadRequest with default headers values
func NewProjectCreateBadRequest() *ProjectCreateBadRequest {
	return &ProjectCreateBadRequest{}
}

/*ProjectCreateBadRequest handles this case with default header values.

Bad request
*/
type ProjectCreateBadRequest struct {
}

func (o *ProjectCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /projects][%d] projectCreateBadRequest ", 400)
}

func (o *ProjectCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectCreateDefault creates a ProjectCreateDefault with default headers values
func NewProjectCreateDefault(code int) *ProjectCreateDefault {
	return &ProjectCreateDefault{
		_statusCode: code,
	}
}

/*ProjectCreateDefault handles this case with default header values.

Unexpected error
*/
type ProjectCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the project create default response
func (o *ProjectCreateDefault) Code() int {
	return o._statusCode
}

func (o *ProjectCreateDefault) Error() string {
	return fmt.Sprintf("[POST /projects][%d] ProjectCreate default ", o._statusCode)
}

func (o *ProjectCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
