// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ProjectGetEdgesReader is a Reader for the ProjectGetEdges structure.
type ProjectGetEdgesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectGetEdgesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectGetEdgesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectGetEdgesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectGetEdgesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectGetEdgesOK creates a ProjectGetEdgesOK with default headers values
func NewProjectGetEdgesOK() *ProjectGetEdgesOK {
	return &ProjectGetEdgesOK{}
}

/*ProjectGetEdgesOK handles this case with default header values.

Ok
*/
type ProjectGetEdgesOK struct {
	Payload []*models.Edge
}

func (o *ProjectGetEdgesOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/edges][%d] projectGetEdgesOK  %+v", 200, o.Payload)
}

func (o *ProjectGetEdgesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectGetEdgesBadRequest creates a ProjectGetEdgesBadRequest with default headers values
func NewProjectGetEdgesBadRequest() *ProjectGetEdgesBadRequest {
	return &ProjectGetEdgesBadRequest{}
}

/*ProjectGetEdgesBadRequest handles this case with default header values.

Bad request
*/
type ProjectGetEdgesBadRequest struct {
}

func (o *ProjectGetEdgesBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/edges][%d] projectGetEdgesBadRequest ", 400)
}

func (o *ProjectGetEdgesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectGetEdgesDefault creates a ProjectGetEdgesDefault with default headers values
func NewProjectGetEdgesDefault(code int) *ProjectGetEdgesDefault {
	return &ProjectGetEdgesDefault{
		_statusCode: code,
	}
}

/*ProjectGetEdgesDefault handles this case with default header values.

Unexpected error
*/
type ProjectGetEdgesDefault struct {
	_statusCode int
}

// Code gets the status code for the project get edges default response
func (o *ProjectGetEdgesDefault) Code() int {
	return o._statusCode
}

func (o *ProjectGetEdgesDefault) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/edges][%d] ProjectGetEdges default ", o._statusCode)
}

func (o *ProjectGetEdgesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
