// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ProjectGetCloudCredsReader is a Reader for the ProjectGetCloudCreds structure.
type ProjectGetCloudCredsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectGetCloudCredsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectGetCloudCredsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectGetCloudCredsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectGetCloudCredsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectGetCloudCredsOK creates a ProjectGetCloudCredsOK with default headers values
func NewProjectGetCloudCredsOK() *ProjectGetCloudCredsOK {
	return &ProjectGetCloudCredsOK{}
}

/*ProjectGetCloudCredsOK handles this case with default header values.

Ok
*/
type ProjectGetCloudCredsOK struct {
	Payload []*models.CloudCreds
}

func (o *ProjectGetCloudCredsOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/cloudcreds][%d] projectGetCloudCredsOK  %+v", 200, o.Payload)
}

func (o *ProjectGetCloudCredsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectGetCloudCredsBadRequest creates a ProjectGetCloudCredsBadRequest with default headers values
func NewProjectGetCloudCredsBadRequest() *ProjectGetCloudCredsBadRequest {
	return &ProjectGetCloudCredsBadRequest{}
}

/*ProjectGetCloudCredsBadRequest handles this case with default header values.

Bad request
*/
type ProjectGetCloudCredsBadRequest struct {
}

func (o *ProjectGetCloudCredsBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/cloudcreds][%d] projectGetCloudCredsBadRequest ", 400)
}

func (o *ProjectGetCloudCredsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectGetCloudCredsDefault creates a ProjectGetCloudCredsDefault with default headers values
func NewProjectGetCloudCredsDefault(code int) *ProjectGetCloudCredsDefault {
	return &ProjectGetCloudCredsDefault{
		_statusCode: code,
	}
}

/*ProjectGetCloudCredsDefault handles this case with default header values.

Unexpected error
*/
type ProjectGetCloudCredsDefault struct {
	_statusCode int
}

// Code gets the status code for the project get cloud creds default response
func (o *ProjectGetCloudCredsDefault) Code() int {
	return o._statusCode
}

func (o *ProjectGetCloudCredsDefault) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/cloudcreds][%d] ProjectGetCloudCreds default ", o._statusCode)
}

func (o *ProjectGetCloudCredsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
