// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectGetContainerRegistriesParams creates a new ProjectGetContainerRegistriesParams object
// with the default values initialized.
func NewProjectGetContainerRegistriesParams() *ProjectGetContainerRegistriesParams {
	var ()
	return &ProjectGetContainerRegistriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectGetContainerRegistriesParamsWithTimeout creates a new ProjectGetContainerRegistriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectGetContainerRegistriesParamsWithTimeout(timeout time.Duration) *ProjectGetContainerRegistriesParams {
	var ()
	return &ProjectGetContainerRegistriesParams{

		timeout: timeout,
	}
}

// NewProjectGetContainerRegistriesParamsWithContext creates a new ProjectGetContainerRegistriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectGetContainerRegistriesParamsWithContext(ctx context.Context) *ProjectGetContainerRegistriesParams {
	var ()
	return &ProjectGetContainerRegistriesParams{

		Context: ctx,
	}
}

// NewProjectGetContainerRegistriesParamsWithHTTPClient creates a new ProjectGetContainerRegistriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectGetContainerRegistriesParamsWithHTTPClient(client *http.Client) *ProjectGetContainerRegistriesParams {
	var ()
	return &ProjectGetContainerRegistriesParams{
		HTTPClient: client,
	}
}

/*ProjectGetContainerRegistriesParams contains all the parameters to send to the API endpoint
for the project get container registries operation typically these are written to a http.Request
*/
type ProjectGetContainerRegistriesParams struct {

	/*ProjectID
	  ID for the project

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) WithTimeout(timeout time.Duration) *ProjectGetContainerRegistriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) WithContext(ctx context.Context) *ProjectGetContainerRegistriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) WithHTTPClient(client *http.Client) *ProjectGetContainerRegistriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) WithProjectID(projectID string) *ProjectGetContainerRegistriesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the project get container registries params
func (o *ProjectGetContainerRegistriesParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectGetContainerRegistriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
