// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ScriptRuntimeUpdateV2Reader is a Reader for the ScriptRuntimeUpdateV2 structure.
type ScriptRuntimeUpdateV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScriptRuntimeUpdateV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewScriptRuntimeUpdateV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewScriptRuntimeUpdateV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewScriptRuntimeUpdateV2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewScriptRuntimeUpdateV2OK creates a ScriptRuntimeUpdateV2OK with default headers values
func NewScriptRuntimeUpdateV2OK() *ScriptRuntimeUpdateV2OK {
	return &ScriptRuntimeUpdateV2OK{}
}

/*ScriptRuntimeUpdateV2OK handles this case with default header values.

Ok
*/
type ScriptRuntimeUpdateV2OK struct {
	Payload *models.UpdateDocumentResponse
}

func (o *ScriptRuntimeUpdateV2OK) Error() string {
	return fmt.Sprintf("[PUT /scriptruntimes/{id}][%d] scriptRuntimeUpdateV2OK  %+v", 200, o.Payload)
}

func (o *ScriptRuntimeUpdateV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScriptRuntimeUpdateV2BadRequest creates a ScriptRuntimeUpdateV2BadRequest with default headers values
func NewScriptRuntimeUpdateV2BadRequest() *ScriptRuntimeUpdateV2BadRequest {
	return &ScriptRuntimeUpdateV2BadRequest{}
}

/*ScriptRuntimeUpdateV2BadRequest handles this case with default header values.

Bad request
*/
type ScriptRuntimeUpdateV2BadRequest struct {
}

func (o *ScriptRuntimeUpdateV2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scriptruntimes/{id}][%d] scriptRuntimeUpdateV2BadRequest ", 400)
}

func (o *ScriptRuntimeUpdateV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScriptRuntimeUpdateV2Default creates a ScriptRuntimeUpdateV2Default with default headers values
func NewScriptRuntimeUpdateV2Default(code int) *ScriptRuntimeUpdateV2Default {
	return &ScriptRuntimeUpdateV2Default{
		_statusCode: code,
	}
}

/*ScriptRuntimeUpdateV2Default handles this case with default header values.

Unexpected error
*/
type ScriptRuntimeUpdateV2Default struct {
	_statusCode int
}

// Code gets the status code for the script runtime update v2 default response
func (o *ScriptRuntimeUpdateV2Default) Code() int {
	return o._statusCode
}

func (o *ScriptRuntimeUpdateV2Default) Error() string {
	return fmt.Sprintf("[PUT /scriptruntimes/{id}][%d] ScriptRuntimeUpdateV2 default ", o._statusCode)
}

func (o *ScriptRuntimeUpdateV2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
