// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ScriptRuntimeGetReader is a Reader for the ScriptRuntimeGet structure.
type ScriptRuntimeGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScriptRuntimeGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewScriptRuntimeGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewScriptRuntimeGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewScriptRuntimeGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewScriptRuntimeGetOK creates a ScriptRuntimeGetOK with default headers values
func NewScriptRuntimeGetOK() *ScriptRuntimeGetOK {
	return &ScriptRuntimeGetOK{}
}

/*ScriptRuntimeGetOK handles this case with default header values.

Ok
*/
type ScriptRuntimeGetOK struct {
	Payload *models.ScriptRuntime
}

func (o *ScriptRuntimeGetOK) Error() string {
	return fmt.Sprintf("[GET /scriptruntimes/{id}][%d] scriptRuntimeGetOK  %+v", 200, o.Payload)
}

func (o *ScriptRuntimeGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScriptRuntime)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScriptRuntimeGetBadRequest creates a ScriptRuntimeGetBadRequest with default headers values
func NewScriptRuntimeGetBadRequest() *ScriptRuntimeGetBadRequest {
	return &ScriptRuntimeGetBadRequest{}
}

/*ScriptRuntimeGetBadRequest handles this case with default header values.

Bad request
*/
type ScriptRuntimeGetBadRequest struct {
}

func (o *ScriptRuntimeGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /scriptruntimes/{id}][%d] scriptRuntimeGetBadRequest ", 400)
}

func (o *ScriptRuntimeGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScriptRuntimeGetDefault creates a ScriptRuntimeGetDefault with default headers values
func NewScriptRuntimeGetDefault(code int) *ScriptRuntimeGetDefault {
	return &ScriptRuntimeGetDefault{
		_statusCode: code,
	}
}

/*ScriptRuntimeGetDefault handles this case with default header values.

Unexpected error
*/
type ScriptRuntimeGetDefault struct {
	_statusCode int
}

// Code gets the status code for the script runtime get default response
func (o *ScriptRuntimeGetDefault) Code() int {
	return o._statusCode
}

func (o *ScriptRuntimeGetDefault) Error() string {
	return fmt.Sprintf("[GET /scriptruntimes/{id}][%d] ScriptRuntimeGet default ", o._statusCode)
}

func (o *ScriptRuntimeGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
