// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// ScriptCreateReader is a Reader for the ScriptCreate structure.
type ScriptCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScriptCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewScriptCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewScriptCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewScriptCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewScriptCreateOK creates a ScriptCreateOK with default headers values
func NewScriptCreateOK() *ScriptCreateOK {
	return &ScriptCreateOK{}
}

/*ScriptCreateOK handles this case with default header values.

Ok
*/
type ScriptCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *ScriptCreateOK) Error() string {
	return fmt.Sprintf("[POST /scripts][%d] scriptCreateOK  %+v", 200, o.Payload)
}

func (o *ScriptCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScriptCreateBadRequest creates a ScriptCreateBadRequest with default headers values
func NewScriptCreateBadRequest() *ScriptCreateBadRequest {
	return &ScriptCreateBadRequest{}
}

/*ScriptCreateBadRequest handles this case with default header values.

Bad request
*/
type ScriptCreateBadRequest struct {
}

func (o *ScriptCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /scripts][%d] scriptCreateBadRequest ", 400)
}

func (o *ScriptCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScriptCreateDefault creates a ScriptCreateDefault with default headers values
func NewScriptCreateDefault(code int) *ScriptCreateDefault {
	return &ScriptCreateDefault{
		_statusCode: code,
	}
}

/*ScriptCreateDefault handles this case with default header values.

Unexpected error
*/
type ScriptCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the script create default response
func (o *ScriptCreateDefault) Code() int {
	return o._statusCode
}

func (o *ScriptCreateDefault) Error() string {
	return fmt.Sprintf("[POST /scripts][%d] ScriptCreate default ", o._statusCode)
}

func (o *ScriptCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
