// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewScriptListParams creates a new ScriptListParams object
// with the default values initialized.
func NewScriptListParams() *ScriptListParams {
	var ()
	return &ScriptListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewScriptListParamsWithTimeout creates a new ScriptListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewScriptListParamsWithTimeout(timeout time.Duration) *ScriptListParams {
	var ()
	return &ScriptListParams{

		timeout: timeout,
	}
}

// NewScriptListParamsWithContext creates a new ScriptListParams object
// with the default values initialized, and the ability to set a context for a request
func NewScriptListParamsWithContext(ctx context.Context) *ScriptListParams {
	var ()
	return &ScriptListParams{

		Context: ctx,
	}
}

// NewScriptListParamsWithHTTPClient creates a new ScriptListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewScriptListParamsWithHTTPClient(client *http.Client) *ScriptListParams {
	var ()
	return &ScriptListParams{
		HTTPClient: client,
	}
}

/*ScriptListParams contains all the parameters to send to the API endpoint
for the script list operation typically these are written to a http.Request
*/
type ScriptListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the script list params
func (o *ScriptListParams) WithTimeout(timeout time.Duration) *ScriptListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the script list params
func (o *ScriptListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the script list params
func (o *ScriptListParams) WithContext(ctx context.Context) *ScriptListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the script list params
func (o *ScriptListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the script list params
func (o *ScriptListParams) WithHTTPClient(client *http.Client) *ScriptListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the script list params
func (o *ScriptListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the script list params
func (o *ScriptListParams) WithAuthorization(authorization string) *ScriptListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the script list params
func (o *ScriptListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *ScriptListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
