// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// SensorCreateReader is a Reader for the SensorCreate structure.
type SensorCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SensorCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSensorCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSensorCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewSensorCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSensorCreateOK creates a SensorCreateOK with default headers values
func NewSensorCreateOK() *SensorCreateOK {
	return &SensorCreateOK{}
}

/*SensorCreateOK handles this case with default header values.

Ok
*/
type SensorCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *SensorCreateOK) Error() string {
	return fmt.Sprintf("[POST /sensors][%d] sensorCreateOK  %+v", 200, o.Payload)
}

func (o *SensorCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSensorCreateBadRequest creates a SensorCreateBadRequest with default headers values
func NewSensorCreateBadRequest() *SensorCreateBadRequest {
	return &SensorCreateBadRequest{}
}

/*SensorCreateBadRequest handles this case with default header values.

Bad request
*/
type SensorCreateBadRequest struct {
}

func (o *SensorCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /sensors][%d] sensorCreateBadRequest ", 400)
}

func (o *SensorCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSensorCreateDefault creates a SensorCreateDefault with default headers values
func NewSensorCreateDefault(code int) *SensorCreateDefault {
	return &SensorCreateDefault{
		_statusCode: code,
	}
}

/*SensorCreateDefault handles this case with default header values.

Unexpected error
*/
type SensorCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the sensor create default response
func (o *SensorCreateDefault) Code() int {
	return o._statusCode
}

func (o *SensorCreateDefault) Error() string {
	return fmt.Sprintf("[POST /sensors][%d] SensorCreate default ", o._statusCode)
}

func (o *SensorCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
