// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/xiiot/client/models"
)

// TenantPropsUpdateReader is a Reader for the TenantPropsUpdate structure.
type TenantPropsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantPropsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTenantPropsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewTenantPropsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewTenantPropsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTenantPropsUpdateOK creates a TenantPropsUpdateOK with default headers values
func NewTenantPropsUpdateOK() *TenantPropsUpdateOK {
	return &TenantPropsUpdateOK{}
}

/*TenantPropsUpdateOK handles this case with default header values.

Ok
*/
type TenantPropsUpdateOK struct {
	Payload *models.UpdateDocumentResponse
}

func (o *TenantPropsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /tenantprops/{id}][%d] tenantPropsUpdateOK  %+v", 200, o.Payload)
}

func (o *TenantPropsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTenantPropsUpdateBadRequest creates a TenantPropsUpdateBadRequest with default headers values
func NewTenantPropsUpdateBadRequest() *TenantPropsUpdateBadRequest {
	return &TenantPropsUpdateBadRequest{}
}

/*TenantPropsUpdateBadRequest handles this case with default header values.

Bad request
*/
type TenantPropsUpdateBadRequest struct {
}

func (o *TenantPropsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /tenantprops/{id}][%d] tenantPropsUpdateBadRequest ", 400)
}

func (o *TenantPropsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTenantPropsUpdateDefault creates a TenantPropsUpdateDefault with default headers values
func NewTenantPropsUpdateDefault(code int) *TenantPropsUpdateDefault {
	return &TenantPropsUpdateDefault{
		_statusCode: code,
	}
}

/*TenantPropsUpdateDefault handles this case with default header values.

Unexpected error
*/
type TenantPropsUpdateDefault struct {
	_statusCode int
}

// Code gets the status code for the tenant props update default response
func (o *TenantPropsUpdateDefault) Code() int {
	return o._statusCode
}

func (o *TenantPropsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /tenantprops/{id}][%d] TenantPropsUpdate default ", o._statusCode)
}

func (o *TenantPropsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
