// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// ApplicationCreateReader is a Reader for the ApplicationCreate structure.
type ApplicationCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewApplicationCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewApplicationCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewApplicationCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationCreateOK creates a ApplicationCreateOK with default headers values
func NewApplicationCreateOK() *ApplicationCreateOK {
	return &ApplicationCreateOK{}
}

/*ApplicationCreateOK handles this case with default header values.

Ok
*/
type ApplicationCreateOK struct {
	Payload *models.CreateDocumentResponse
}

func (o *ApplicationCreateOK) Error() string {
	return fmt.Sprintf("[POST /application][%d] applicationCreateOK  %+v", 200, o.Payload)
}

func (o *ApplicationCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationCreateBadRequest creates a ApplicationCreateBadRequest with default headers values
func NewApplicationCreateBadRequest() *ApplicationCreateBadRequest {
	return &ApplicationCreateBadRequest{}
}

/*ApplicationCreateBadRequest handles this case with default header values.

Bad request
*/
type ApplicationCreateBadRequest struct {
}

func (o *ApplicationCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /application][%d] applicationCreateBadRequest ", 400)
}

func (o *ApplicationCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplicationCreateDefault creates a ApplicationCreateDefault with default headers values
func NewApplicationCreateDefault(code int) *ApplicationCreateDefault {
	return &ApplicationCreateDefault{
		_statusCode: code,
	}
}

/*ApplicationCreateDefault handles this case with default header values.

Unexpected error
*/
type ApplicationCreateDefault struct {
	_statusCode int
}

// Code gets the status code for the application create default response
func (o *ApplicationCreateDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationCreateDefault) Error() string {
	return fmt.Sprintf("[POST /application][%d] ApplicationCreate default ", o._statusCode)
}

func (o *ApplicationCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
