// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewApplicationListParams creates a new ApplicationListParams object
// with the default values initialized.
func NewApplicationListParams() *ApplicationListParams {
	var ()
	return &ApplicationListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationListParamsWithTimeout creates a new ApplicationListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApplicationListParamsWithTimeout(timeout time.Duration) *ApplicationListParams {
	var ()
	return &ApplicationListParams{

		timeout: timeout,
	}
}

// NewApplicationListParamsWithContext creates a new ApplicationListParams object
// with the default values initialized, and the ability to set a context for a request
func NewApplicationListParamsWithContext(ctx context.Context) *ApplicationListParams {
	var ()
	return &ApplicationListParams{

		Context: ctx,
	}
}

// NewApplicationListParamsWithHTTPClient creates a new ApplicationListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApplicationListParamsWithHTTPClient(client *http.Client) *ApplicationListParams {
	var ()
	return &ApplicationListParams{
		HTTPClient: client,
	}
}

/*ApplicationListParams contains all the parameters to send to the API endpoint
for the application list operation typically these are written to a http.Request
*/
type ApplicationListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the application list params
func (o *ApplicationListParams) WithTimeout(timeout time.Duration) *ApplicationListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application list params
func (o *ApplicationListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application list params
func (o *ApplicationListParams) WithContext(ctx context.Context) *ApplicationListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application list params
func (o *ApplicationListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application list params
func (o *ApplicationListParams) WithHTTPClient(client *http.Client) *ApplicationListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application list params
func (o *ApplicationListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the application list params
func (o *ApplicationListParams) WithAuthorization(authorization string) *ApplicationListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the application list params
func (o *ApplicationListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
