// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCategoryListParams creates a new CategoryListParams object
// with the default values initialized.
func NewCategoryListParams() *CategoryListParams {
	var ()
	return &CategoryListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCategoryListParamsWithTimeout creates a new CategoryListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCategoryListParamsWithTimeout(timeout time.Duration) *CategoryListParams {
	var ()
	return &CategoryListParams{

		timeout: timeout,
	}
}

// NewCategoryListParamsWithContext creates a new CategoryListParams object
// with the default values initialized, and the ability to set a context for a request
func NewCategoryListParamsWithContext(ctx context.Context) *CategoryListParams {
	var ()
	return &CategoryListParams{

		Context: ctx,
	}
}

// NewCategoryListParamsWithHTTPClient creates a new CategoryListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCategoryListParamsWithHTTPClient(client *http.Client) *CategoryListParams {
	var ()
	return &CategoryListParams{
		HTTPClient: client,
	}
}

/*CategoryListParams contains all the parameters to send to the API endpoint
for the category list operation typically these are written to a http.Request
*/
type CategoryListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the category list params
func (o *CategoryListParams) WithTimeout(timeout time.Duration) *CategoryListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the category list params
func (o *CategoryListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the category list params
func (o *CategoryListParams) WithContext(ctx context.Context) *CategoryListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the category list params
func (o *CategoryListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the category list params
func (o *CategoryListParams) WithHTTPClient(client *http.Client) *CategoryListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the category list params
func (o *CategoryListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the category list params
func (o *CategoryListParams) WithAuthorization(authorization string) *CategoryListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the category list params
func (o *CategoryListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *CategoryListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
