// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// CategoryListReader is a Reader for the CategoryList structure.
type CategoryListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CategoryListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCategoryListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCategoryListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCategoryListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCategoryListOK creates a CategoryListOK with default headers values
func NewCategoryListOK() *CategoryListOK {
	return &CategoryListOK{}
}

/*CategoryListOK handles this case with default header values.

Ok
*/
type CategoryListOK struct {
	Payload []*models.Category
}

func (o *CategoryListOK) Error() string {
	return fmt.Sprintf("[GET /categories][%d] categoryListOK  %+v", 200, o.Payload)
}

func (o *CategoryListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCategoryListBadRequest creates a CategoryListBadRequest with default headers values
func NewCategoryListBadRequest() *CategoryListBadRequest {
	return &CategoryListBadRequest{}
}

/*CategoryListBadRequest handles this case with default header values.

Bad request
*/
type CategoryListBadRequest struct {
}

func (o *CategoryListBadRequest) Error() string {
	return fmt.Sprintf("[GET /categories][%d] categoryListBadRequest ", 400)
}

func (o *CategoryListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCategoryListDefault creates a CategoryListDefault with default headers values
func NewCategoryListDefault(code int) *CategoryListDefault {
	return &CategoryListDefault{
		_statusCode: code,
	}
}

/*CategoryListDefault handles this case with default header values.

Unexpected error
*/
type CategoryListDefault struct {
	_statusCode int
}

// Code gets the status code for the category list default response
func (o *CategoryListDefault) Code() int {
	return o._statusCode
}

func (o *CategoryListDefault) Error() string {
	return fmt.Sprintf("[GET /categories][%d] CategoryList default ", o._statusCode)
}

func (o *CategoryListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
