// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// CategoryDeleteReader is a Reader for the CategoryDelete structure.
type CategoryDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CategoryDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCategoryDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCategoryDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCategoryDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCategoryDeleteOK creates a CategoryDeleteOK with default headers values
func NewCategoryDeleteOK() *CategoryDeleteOK {
	return &CategoryDeleteOK{}
}

/*CategoryDeleteOK handles this case with default header values.

Ok
*/
type CategoryDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *CategoryDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] categoryDeleteOK  %+v", 200, o.Payload)
}

func (o *CategoryDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCategoryDeleteBadRequest creates a CategoryDeleteBadRequest with default headers values
func NewCategoryDeleteBadRequest() *CategoryDeleteBadRequest {
	return &CategoryDeleteBadRequest{}
}

/*CategoryDeleteBadRequest handles this case with default header values.

Bad request
*/
type CategoryDeleteBadRequest struct {
}

func (o *CategoryDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] categoryDeleteBadRequest ", 400)
}

func (o *CategoryDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCategoryDeleteDefault creates a CategoryDeleteDefault with default headers values
func NewCategoryDeleteDefault(code int) *CategoryDeleteDefault {
	return &CategoryDeleteDefault{
		_statusCode: code,
	}
}

/*CategoryDeleteDefault handles this case with default header values.

Unexpected error
*/
type CategoryDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the category delete default response
func (o *CategoryDeleteDefault) Code() int {
	return o._statusCode
}

func (o *CategoryDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] CategoryDelete default ", o._statusCode)
}

func (o *CategoryDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
