// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// CloudCredsListReader is a Reader for the CloudCredsList structure.
type CloudCredsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CloudCredsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCloudCredsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCloudCredsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCloudCredsListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCloudCredsListOK creates a CloudCredsListOK with default headers values
func NewCloudCredsListOK() *CloudCredsListOK {
	return &CloudCredsListOK{}
}

/*CloudCredsListOK handles this case with default header values.

Ok
*/
type CloudCredsListOK struct {
	Payload []*models.CloudCreds
}

func (o *CloudCredsListOK) Error() string {
	return fmt.Sprintf("[GET /cloudcreds][%d] cloudCredsListOK  %+v", 200, o.Payload)
}

func (o *CloudCredsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudCredsListBadRequest creates a CloudCredsListBadRequest with default headers values
func NewCloudCredsListBadRequest() *CloudCredsListBadRequest {
	return &CloudCredsListBadRequest{}
}

/*CloudCredsListBadRequest handles this case with default header values.

Bad request
*/
type CloudCredsListBadRequest struct {
}

func (o *CloudCredsListBadRequest) Error() string {
	return fmt.Sprintf("[GET /cloudcreds][%d] cloudCredsListBadRequest ", 400)
}

func (o *CloudCredsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCloudCredsListDefault creates a CloudCredsListDefault with default headers values
func NewCloudCredsListDefault(code int) *CloudCredsListDefault {
	return &CloudCredsListDefault{
		_statusCode: code,
	}
}

/*CloudCredsListDefault handles this case with default header values.

Unexpected error
*/
type CloudCredsListDefault struct {
	_statusCode int
}

// Code gets the status code for the cloud creds list default response
func (o *CloudCredsListDefault) Code() int {
	return o._statusCode
}

func (o *CloudCredsListDefault) Error() string {
	return fmt.Sprintf("[GET /cloudcreds][%d] CloudCredsList default ", o._statusCode)
}

func (o *CloudCredsListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
