// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// CommonNestedAggregatesReader is a Reader for the CommonNestedAggregates structure.
type CommonNestedAggregatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CommonNestedAggregatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCommonNestedAggregatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCommonNestedAggregatesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewCommonNestedAggregatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCommonNestedAggregatesOK creates a CommonNestedAggregatesOK with default headers values
func NewCommonNestedAggregatesOK() *CommonNestedAggregatesOK {
	return &CommonNestedAggregatesOK{}
}

/*CommonNestedAggregatesOK handles this case with default header values.

Ok
*/
type CommonNestedAggregatesOK struct {
	Payload []*models.AggregateInfo
}

func (o *CommonNestedAggregatesOK) Error() string {
	return fmt.Sprintf("[POST /common/nestedAggregates][%d] commonNestedAggregatesOK  %+v", 200, o.Payload)
}

func (o *CommonNestedAggregatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCommonNestedAggregatesBadRequest creates a CommonNestedAggregatesBadRequest with default headers values
func NewCommonNestedAggregatesBadRequest() *CommonNestedAggregatesBadRequest {
	return &CommonNestedAggregatesBadRequest{}
}

/*CommonNestedAggregatesBadRequest handles this case with default header values.

Bad request
*/
type CommonNestedAggregatesBadRequest struct {
}

func (o *CommonNestedAggregatesBadRequest) Error() string {
	return fmt.Sprintf("[POST /common/nestedAggregates][%d] commonNestedAggregatesBadRequest ", 400)
}

func (o *CommonNestedAggregatesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCommonNestedAggregatesDefault creates a CommonNestedAggregatesDefault with default headers values
func NewCommonNestedAggregatesDefault(code int) *CommonNestedAggregatesDefault {
	return &CommonNestedAggregatesDefault{
		_statusCode: code,
	}
}

/*CommonNestedAggregatesDefault handles this case with default header values.

Unexpected error
*/
type CommonNestedAggregatesDefault struct {
	_statusCode int
}

// Code gets the status code for the common nested aggregates default response
func (o *CommonNestedAggregatesDefault) Code() int {
	return o._statusCode
}

func (o *CommonNestedAggregatesDefault) Error() string {
	return fmt.Sprintf("[POST /common/nestedAggregates][%d] CommonNestedAggregates default ", o._statusCode)
}

func (o *CommonNestedAggregatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
