// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewContainerRegistryListParams creates a new ContainerRegistryListParams object
// with the default values initialized.
func NewContainerRegistryListParams() *ContainerRegistryListParams {
	var ()
	return &ContainerRegistryListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContainerRegistryListParamsWithTimeout creates a new ContainerRegistryListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContainerRegistryListParamsWithTimeout(timeout time.Duration) *ContainerRegistryListParams {
	var ()
	return &ContainerRegistryListParams{

		timeout: timeout,
	}
}

// NewContainerRegistryListParamsWithContext creates a new ContainerRegistryListParams object
// with the default values initialized, and the ability to set a context for a request
func NewContainerRegistryListParamsWithContext(ctx context.Context) *ContainerRegistryListParams {
	var ()
	return &ContainerRegistryListParams{

		Context: ctx,
	}
}

// NewContainerRegistryListParamsWithHTTPClient creates a new ContainerRegistryListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContainerRegistryListParamsWithHTTPClient(client *http.Client) *ContainerRegistryListParams {
	var ()
	return &ContainerRegistryListParams{
		HTTPClient: client,
	}
}

/*ContainerRegistryListParams contains all the parameters to send to the API endpoint
for the container registry list operation typically these are written to a http.Request
*/
type ContainerRegistryListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the container registry list params
func (o *ContainerRegistryListParams) WithTimeout(timeout time.Duration) *ContainerRegistryListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the container registry list params
func (o *ContainerRegistryListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the container registry list params
func (o *ContainerRegistryListParams) WithContext(ctx context.Context) *ContainerRegistryListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the container registry list params
func (o *ContainerRegistryListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the container registry list params
func (o *ContainerRegistryListParams) WithHTTPClient(client *http.Client) *ContainerRegistryListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the container registry list params
func (o *ContainerRegistryListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the container registry list params
func (o *ContainerRegistryListParams) WithAuthorization(authorization string) *ContainerRegistryListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the container registry list params
func (o *ContainerRegistryListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *ContainerRegistryListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
