// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// ContainerRegistryDeleteReader is a Reader for the ContainerRegistryDelete structure.
type ContainerRegistryDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerRegistryDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewContainerRegistryDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewContainerRegistryDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewContainerRegistryDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewContainerRegistryDeleteOK creates a ContainerRegistryDeleteOK with default headers values
func NewContainerRegistryDeleteOK() *ContainerRegistryDeleteOK {
	return &ContainerRegistryDeleteOK{}
}

/*ContainerRegistryDeleteOK handles this case with default header values.

Ok
*/
type ContainerRegistryDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *ContainerRegistryDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /containerregistries/{id}][%d] containerRegistryDeleteOK  %+v", 200, o.Payload)
}

func (o *ContainerRegistryDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerRegistryDeleteBadRequest creates a ContainerRegistryDeleteBadRequest with default headers values
func NewContainerRegistryDeleteBadRequest() *ContainerRegistryDeleteBadRequest {
	return &ContainerRegistryDeleteBadRequest{}
}

/*ContainerRegistryDeleteBadRequest handles this case with default header values.

Bad request
*/
type ContainerRegistryDeleteBadRequest struct {
}

func (o *ContainerRegistryDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /containerregistries/{id}][%d] containerRegistryDeleteBadRequest ", 400)
}

func (o *ContainerRegistryDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerRegistryDeleteDefault creates a ContainerRegistryDeleteDefault with default headers values
func NewContainerRegistryDeleteDefault(code int) *ContainerRegistryDeleteDefault {
	return &ContainerRegistryDeleteDefault{
		_statusCode: code,
	}
}

/*ContainerRegistryDeleteDefault handles this case with default header values.

Unexpected error
*/
type ContainerRegistryDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the container registry delete default response
func (o *ContainerRegistryDeleteDefault) Code() int {
	return o._statusCode
}

func (o *ContainerRegistryDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /containerregistries/{id}][%d] ContainerRegistryDelete default ", o._statusCode)
}

func (o *ContainerRegistryDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
