// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataSourceListParams creates a new DataSourceListParams object
// with the default values initialized.
func NewDataSourceListParams() *DataSourceListParams {
	var ()
	return &DataSourceListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataSourceListParamsWithTimeout creates a new DataSourceListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataSourceListParamsWithTimeout(timeout time.Duration) *DataSourceListParams {
	var ()
	return &DataSourceListParams{

		timeout: timeout,
	}
}

// NewDataSourceListParamsWithContext creates a new DataSourceListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataSourceListParamsWithContext(ctx context.Context) *DataSourceListParams {
	var ()
	return &DataSourceListParams{

		Context: ctx,
	}
}

// NewDataSourceListParamsWithHTTPClient creates a new DataSourceListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataSourceListParamsWithHTTPClient(client *http.Client) *DataSourceListParams {
	var ()
	return &DataSourceListParams{
		HTTPClient: client,
	}
}

/*DataSourceListParams contains all the parameters to send to the API endpoint
for the data source list operation typically these are written to a http.Request
*/
type DataSourceListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data source list params
func (o *DataSourceListParams) WithTimeout(timeout time.Duration) *DataSourceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data source list params
func (o *DataSourceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data source list params
func (o *DataSourceListParams) WithContext(ctx context.Context) *DataSourceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data source list params
func (o *DataSourceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data source list params
func (o *DataSourceListParams) WithHTTPClient(client *http.Client) *DataSourceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data source list params
func (o *DataSourceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the data source list params
func (o *DataSourceListParams) WithAuthorization(authorization string) *DataSourceListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the data source list params
func (o *DataSourceListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *DataSourceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
