// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// DockerProfileListReader is a Reader for the DockerProfileList structure.
type DockerProfileListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DockerProfileListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDockerProfileListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDockerProfileListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDockerProfileListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDockerProfileListOK creates a DockerProfileListOK with default headers values
func NewDockerProfileListOK() *DockerProfileListOK {
	return &DockerProfileListOK{}
}

/*DockerProfileListOK handles this case with default header values.

Ok
*/
type DockerProfileListOK struct {
	Payload []*models.DockerProfile
}

func (o *DockerProfileListOK) Error() string {
	return fmt.Sprintf("[GET /dockerprofiles][%d] dockerProfileListOK  %+v", 200, o.Payload)
}

func (o *DockerProfileListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDockerProfileListBadRequest creates a DockerProfileListBadRequest with default headers values
func NewDockerProfileListBadRequest() *DockerProfileListBadRequest {
	return &DockerProfileListBadRequest{}
}

/*DockerProfileListBadRequest handles this case with default header values.

Bad request
*/
type DockerProfileListBadRequest struct {
}

func (o *DockerProfileListBadRequest) Error() string {
	return fmt.Sprintf("[GET /dockerprofiles][%d] dockerProfileListBadRequest ", 400)
}

func (o *DockerProfileListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDockerProfileListDefault creates a DockerProfileListDefault with default headers values
func NewDockerProfileListDefault(code int) *DockerProfileListDefault {
	return &DockerProfileListDefault{
		_statusCode: code,
	}
}

/*DockerProfileListDefault handles this case with default header values.

Unexpected error
*/
type DockerProfileListDefault struct {
	_statusCode int
}

// Code gets the status code for the docker profile list default response
func (o *DockerProfileListDefault) Code() int {
	return o._statusCode
}

func (o *DockerProfileListDefault) Error() string {
	return fmt.Sprintf("[GET /dockerprofiles][%d] DockerProfileList default ", o._statusCode)
}

func (o *DockerProfileListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
