// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// DockerProfileUpdateV2Reader is a Reader for the DockerProfileUpdateV2 structure.
type DockerProfileUpdateV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DockerProfileUpdateV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDockerProfileUpdateV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDockerProfileUpdateV2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDockerProfileUpdateV2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDockerProfileUpdateV2OK creates a DockerProfileUpdateV2OK with default headers values
func NewDockerProfileUpdateV2OK() *DockerProfileUpdateV2OK {
	return &DockerProfileUpdateV2OK{}
}

/*DockerProfileUpdateV2OK handles this case with default header values.

Ok
*/
type DockerProfileUpdateV2OK struct {
	Payload *models.UpdateDocumentResponse
}

func (o *DockerProfileUpdateV2OK) Error() string {
	return fmt.Sprintf("[PUT /dockerprofiles/{id}][%d] dockerProfileUpdateV2OK  %+v", 200, o.Payload)
}

func (o *DockerProfileUpdateV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDockerProfileUpdateV2BadRequest creates a DockerProfileUpdateV2BadRequest with default headers values
func NewDockerProfileUpdateV2BadRequest() *DockerProfileUpdateV2BadRequest {
	return &DockerProfileUpdateV2BadRequest{}
}

/*DockerProfileUpdateV2BadRequest handles this case with default header values.

Bad request
*/
type DockerProfileUpdateV2BadRequest struct {
}

func (o *DockerProfileUpdateV2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /dockerprofiles/{id}][%d] dockerProfileUpdateV2BadRequest ", 400)
}

func (o *DockerProfileUpdateV2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDockerProfileUpdateV2Default creates a DockerProfileUpdateV2Default with default headers values
func NewDockerProfileUpdateV2Default(code int) *DockerProfileUpdateV2Default {
	return &DockerProfileUpdateV2Default{
		_statusCode: code,
	}
}

/*DockerProfileUpdateV2Default handles this case with default header values.

Unexpected error
*/
type DockerProfileUpdateV2Default struct {
	_statusCode int
}

// Code gets the status code for the docker profile update v2 default response
func (o *DockerProfileUpdateV2Default) Code() int {
	return o._statusCode
}

func (o *DockerProfileUpdateV2Default) Error() string {
	return fmt.Sprintf("[PUT /dockerprofiles/{id}][%d] DockerProfileUpdateV2 default ", o._statusCode)
}

func (o *DockerProfileUpdateV2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
