// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// DockerProfileDeleteReader is a Reader for the DockerProfileDelete structure.
type DockerProfileDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DockerProfileDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDockerProfileDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDockerProfileDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDockerProfileDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDockerProfileDeleteOK creates a DockerProfileDeleteOK with default headers values
func NewDockerProfileDeleteOK() *DockerProfileDeleteOK {
	return &DockerProfileDeleteOK{}
}

/*DockerProfileDeleteOK handles this case with default header values.

Ok
*/
type DockerProfileDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *DockerProfileDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /dockerprofiles/{id}][%d] dockerProfileDeleteOK  %+v", 200, o.Payload)
}

func (o *DockerProfileDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDockerProfileDeleteBadRequest creates a DockerProfileDeleteBadRequest with default headers values
func NewDockerProfileDeleteBadRequest() *DockerProfileDeleteBadRequest {
	return &DockerProfileDeleteBadRequest{}
}

/*DockerProfileDeleteBadRequest handles this case with default header values.

Bad request
*/
type DockerProfileDeleteBadRequest struct {
}

func (o *DockerProfileDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /dockerprofiles/{id}][%d] dockerProfileDeleteBadRequest ", 400)
}

func (o *DockerProfileDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDockerProfileDeleteDefault creates a DockerProfileDeleteDefault with default headers values
func NewDockerProfileDeleteDefault(code int) *DockerProfileDeleteDefault {
	return &DockerProfileDeleteDefault{
		_statusCode: code,
	}
}

/*DockerProfileDeleteDefault handles this case with default header values.

Unexpected error
*/
type DockerProfileDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the docker profile delete default response
func (o *DockerProfileDeleteDefault) Code() int {
	return o._statusCode
}

func (o *DockerProfileDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /dockerprofiles/{id}][%d] DockerProfileDelete default ", o._statusCode)
}

func (o *DockerProfileDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
