// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// EdgeInfoUpdateReader is a Reader for the EdgeInfoUpdate structure.
type EdgeInfoUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeInfoUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEdgeInfoUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEdgeInfoUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEdgeInfoUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeInfoUpdateOK creates a EdgeInfoUpdateOK with default headers values
func NewEdgeInfoUpdateOK() *EdgeInfoUpdateOK {
	return &EdgeInfoUpdateOK{}
}

/*EdgeInfoUpdateOK handles this case with default header values.

Ok
*/
type EdgeInfoUpdateOK struct {
	Payload *models.UpdateDocumentResponse
}

func (o *EdgeInfoUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /edges/{id}/info][%d] edgeInfoUpdateOK  %+v", 200, o.Payload)
}

func (o *EdgeInfoUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeInfoUpdateBadRequest creates a EdgeInfoUpdateBadRequest with default headers values
func NewEdgeInfoUpdateBadRequest() *EdgeInfoUpdateBadRequest {
	return &EdgeInfoUpdateBadRequest{}
}

/*EdgeInfoUpdateBadRequest handles this case with default header values.

Bad request
*/
type EdgeInfoUpdateBadRequest struct {
}

func (o *EdgeInfoUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /edges/{id}/info][%d] edgeInfoUpdateBadRequest ", 400)
}

func (o *EdgeInfoUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeInfoUpdateDefault creates a EdgeInfoUpdateDefault with default headers values
func NewEdgeInfoUpdateDefault(code int) *EdgeInfoUpdateDefault {
	return &EdgeInfoUpdateDefault{
		_statusCode: code,
	}
}

/*EdgeInfoUpdateDefault handles this case with default header values.

Unexpected error
*/
type EdgeInfoUpdateDefault struct {
	_statusCode int
}

// Code gets the status code for the edge info update default response
func (o *EdgeInfoUpdateDefault) Code() int {
	return o._statusCode
}

func (o *EdgeInfoUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /edges/{id}/info][%d] EdgeInfoUpdate default ", o._statusCode)
}

func (o *EdgeInfoUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
