// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// LogEntryDeleteReader is a Reader for the LogEntryDelete structure.
type LogEntryDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogEntryDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLogEntryDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewLogEntryDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewLogEntryDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLogEntryDeleteOK creates a LogEntryDeleteOK with default headers values
func NewLogEntryDeleteOK() *LogEntryDeleteOK {
	return &LogEntryDeleteOK{}
}

/*LogEntryDeleteOK handles this case with default header values.

Ok
*/
type LogEntryDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *LogEntryDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /logs/entries/{id}][%d] logEntryDeleteOK  %+v", 200, o.Payload)
}

func (o *LogEntryDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogEntryDeleteBadRequest creates a LogEntryDeleteBadRequest with default headers values
func NewLogEntryDeleteBadRequest() *LogEntryDeleteBadRequest {
	return &LogEntryDeleteBadRequest{}
}

/*LogEntryDeleteBadRequest handles this case with default header values.

Bad request
*/
type LogEntryDeleteBadRequest struct {
}

func (o *LogEntryDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /logs/entries/{id}][%d] logEntryDeleteBadRequest ", 400)
}

func (o *LogEntryDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLogEntryDeleteDefault creates a LogEntryDeleteDefault with default headers values
func NewLogEntryDeleteDefault(code int) *LogEntryDeleteDefault {
	return &LogEntryDeleteDefault{
		_statusCode: code,
	}
}

/*LogEntryDeleteDefault handles this case with default header values.

Unexpected error
*/
type LogEntryDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the log entry delete default response
func (o *LogEntryDeleteDefault) Code() int {
	return o._statusCode
}

func (o *LogEntryDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /logs/entries/{id}][%d] LogEntryDelete default ", o._statusCode)
}

func (o *LogEntryDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
