// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectGetApplicationsParams creates a new ProjectGetApplicationsParams object
// with the default values initialized.
func NewProjectGetApplicationsParams() *ProjectGetApplicationsParams {
	var ()
	return &ProjectGetApplicationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectGetApplicationsParamsWithTimeout creates a new ProjectGetApplicationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectGetApplicationsParamsWithTimeout(timeout time.Duration) *ProjectGetApplicationsParams {
	var ()
	return &ProjectGetApplicationsParams{

		timeout: timeout,
	}
}

// NewProjectGetApplicationsParamsWithContext creates a new ProjectGetApplicationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectGetApplicationsParamsWithContext(ctx context.Context) *ProjectGetApplicationsParams {
	var ()
	return &ProjectGetApplicationsParams{

		Context: ctx,
	}
}

// NewProjectGetApplicationsParamsWithHTTPClient creates a new ProjectGetApplicationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectGetApplicationsParamsWithHTTPClient(client *http.Client) *ProjectGetApplicationsParams {
	var ()
	return &ProjectGetApplicationsParams{
		HTTPClient: client,
	}
}

/*ProjectGetApplicationsParams contains all the parameters to send to the API endpoint
for the project get applications operation typically these are written to a http.Request
*/
type ProjectGetApplicationsParams struct {

	/*Authorization*/
	Authorization string
	/*ProjectID
	  ID for the project

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the project get applications params
func (o *ProjectGetApplicationsParams) WithTimeout(timeout time.Duration) *ProjectGetApplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project get applications params
func (o *ProjectGetApplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project get applications params
func (o *ProjectGetApplicationsParams) WithContext(ctx context.Context) *ProjectGetApplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project get applications params
func (o *ProjectGetApplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project get applications params
func (o *ProjectGetApplicationsParams) WithHTTPClient(client *http.Client) *ProjectGetApplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project get applications params
func (o *ProjectGetApplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the project get applications params
func (o *ProjectGetApplicationsParams) WithAuthorization(authorization string) *ProjectGetApplicationsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the project get applications params
func (o *ProjectGetApplicationsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithProjectID adds the projectID to the project get applications params
func (o *ProjectGetApplicationsParams) WithProjectID(projectID string) *ProjectGetApplicationsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the project get applications params
func (o *ProjectGetApplicationsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectGetApplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
