// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectGetScriptsParams creates a new ProjectGetScriptsParams object
// with the default values initialized.
func NewProjectGetScriptsParams() *ProjectGetScriptsParams {
	var ()
	return &ProjectGetScriptsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectGetScriptsParamsWithTimeout creates a new ProjectGetScriptsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectGetScriptsParamsWithTimeout(timeout time.Duration) *ProjectGetScriptsParams {
	var ()
	return &ProjectGetScriptsParams{

		timeout: timeout,
	}
}

// NewProjectGetScriptsParamsWithContext creates a new ProjectGetScriptsParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectGetScriptsParamsWithContext(ctx context.Context) *ProjectGetScriptsParams {
	var ()
	return &ProjectGetScriptsParams{

		Context: ctx,
	}
}

// NewProjectGetScriptsParamsWithHTTPClient creates a new ProjectGetScriptsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectGetScriptsParamsWithHTTPClient(client *http.Client) *ProjectGetScriptsParams {
	var ()
	return &ProjectGetScriptsParams{
		HTTPClient: client,
	}
}

/*ProjectGetScriptsParams contains all the parameters to send to the API endpoint
for the project get scripts operation typically these are written to a http.Request
*/
type ProjectGetScriptsParams struct {

	/*Authorization*/
	Authorization string
	/*ProjectID
	  ID for the project

	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the project get scripts params
func (o *ProjectGetScriptsParams) WithTimeout(timeout time.Duration) *ProjectGetScriptsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project get scripts params
func (o *ProjectGetScriptsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project get scripts params
func (o *ProjectGetScriptsParams) WithContext(ctx context.Context) *ProjectGetScriptsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project get scripts params
func (o *ProjectGetScriptsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project get scripts params
func (o *ProjectGetScriptsParams) WithHTTPClient(client *http.Client) *ProjectGetScriptsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project get scripts params
func (o *ProjectGetScriptsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the project get scripts params
func (o *ProjectGetScriptsParams) WithAuthorization(authorization string) *ProjectGetScriptsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the project get scripts params
func (o *ProjectGetScriptsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithProjectID adds the projectID to the project get scripts params
func (o *ProjectGetScriptsParams) WithProjectID(projectID string) *ProjectGetScriptsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the project get scripts params
func (o *ProjectGetScriptsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectGetScriptsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
