// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// ProjectGetUsersReader is a Reader for the ProjectGetUsers structure.
type ProjectGetUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectGetUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectGetUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectGetUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectGetUsersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectGetUsersOK creates a ProjectGetUsersOK with default headers values
func NewProjectGetUsersOK() *ProjectGetUsersOK {
	return &ProjectGetUsersOK{}
}

/*ProjectGetUsersOK handles this case with default header values.

Ok
*/
type ProjectGetUsersOK struct {
	Payload []*models.User
}

func (o *ProjectGetUsersOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/users][%d] projectGetUsersOK  %+v", 200, o.Payload)
}

func (o *ProjectGetUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectGetUsersBadRequest creates a ProjectGetUsersBadRequest with default headers values
func NewProjectGetUsersBadRequest() *ProjectGetUsersBadRequest {
	return &ProjectGetUsersBadRequest{}
}

/*ProjectGetUsersBadRequest handles this case with default header values.

Bad request
*/
type ProjectGetUsersBadRequest struct {
}

func (o *ProjectGetUsersBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/users][%d] projectGetUsersBadRequest ", 400)
}

func (o *ProjectGetUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectGetUsersDefault creates a ProjectGetUsersDefault with default headers values
func NewProjectGetUsersDefault(code int) *ProjectGetUsersDefault {
	return &ProjectGetUsersDefault{
		_statusCode: code,
	}
}

/*ProjectGetUsersDefault handles this case with default header values.

Unexpected error
*/
type ProjectGetUsersDefault struct {
	_statusCode int
}

// Code gets the status code for the project get users default response
func (o *ProjectGetUsersDefault) Code() int {
	return o._statusCode
}

func (o *ProjectGetUsersDefault) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}/users][%d] ProjectGetUsers default ", o._statusCode)
}

func (o *ProjectGetUsersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
