// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// ProjectDeleteReader is a Reader for the ProjectDelete structure.
type ProjectDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewProjectDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectDeleteOK creates a ProjectDeleteOK with default headers values
func NewProjectDeleteOK() *ProjectDeleteOK {
	return &ProjectDeleteOK{}
}

/*ProjectDeleteOK handles this case with default header values.

Ok
*/
type ProjectDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *ProjectDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /projects/{id}][%d] projectDeleteOK  %+v", 200, o.Payload)
}

func (o *ProjectDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectDeleteBadRequest creates a ProjectDeleteBadRequest with default headers values
func NewProjectDeleteBadRequest() *ProjectDeleteBadRequest {
	return &ProjectDeleteBadRequest{}
}

/*ProjectDeleteBadRequest handles this case with default header values.

Bad request
*/
type ProjectDeleteBadRequest struct {
}

func (o *ProjectDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /projects/{id}][%d] projectDeleteBadRequest ", 400)
}

func (o *ProjectDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectDeleteDefault creates a ProjectDeleteDefault with default headers values
func NewProjectDeleteDefault(code int) *ProjectDeleteDefault {
	return &ProjectDeleteDefault{
		_statusCode: code,
	}
}

/*ProjectDeleteDefault handles this case with default header values.

Unexpected error
*/
type ProjectDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the project delete default response
func (o *ProjectDeleteDefault) Code() int {
	return o._statusCode
}

func (o *ProjectDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /projects/{id}][%d] ProjectDelete default ", o._statusCode)
}

func (o *ProjectDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
