// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// QueryEventsReader is a Reader for the QueryEvents structure.
type QueryEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewQueryEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewQueryEventsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewQueryEventsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQueryEventsOK creates a QueryEventsOK with default headers values
func NewQueryEventsOK() *QueryEventsOK {
	return &QueryEventsOK{}
}

/*QueryEventsOK handles this case with default header values.

Ok
*/
type QueryEventsOK struct {
	Payload []*models.Event
}

func (o *QueryEventsOK) Error() string {
	return fmt.Sprintf("[POST /events][%d] queryEventsOK  %+v", 200, o.Payload)
}

func (o *QueryEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryEventsBadRequest creates a QueryEventsBadRequest with default headers values
func NewQueryEventsBadRequest() *QueryEventsBadRequest {
	return &QueryEventsBadRequest{}
}

/*QueryEventsBadRequest handles this case with default header values.

Bad request
*/
type QueryEventsBadRequest struct {
}

func (o *QueryEventsBadRequest) Error() string {
	return fmt.Sprintf("[POST /events][%d] queryEventsBadRequest ", 400)
}

func (o *QueryEventsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryEventsDefault creates a QueryEventsDefault with default headers values
func NewQueryEventsDefault(code int) *QueryEventsDefault {
	return &QueryEventsDefault{
		_statusCode: code,
	}
}

/*QueryEventsDefault handles this case with default header values.

Unexpected error
*/
type QueryEventsDefault struct {
	_statusCode int
}

// Code gets the status code for the query events default response
func (o *QueryEventsDefault) Code() int {
	return o._statusCode
}

func (o *QueryEventsDefault) Error() string {
	return fmt.Sprintf("[POST /events][%d] QueryEvents default ", o._statusCode)
}

func (o *QueryEventsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
