// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewScriptRuntimeListParams creates a new ScriptRuntimeListParams object
// with the default values initialized.
func NewScriptRuntimeListParams() *ScriptRuntimeListParams {
	var ()
	return &ScriptRuntimeListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewScriptRuntimeListParamsWithTimeout creates a new ScriptRuntimeListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewScriptRuntimeListParamsWithTimeout(timeout time.Duration) *ScriptRuntimeListParams {
	var ()
	return &ScriptRuntimeListParams{

		timeout: timeout,
	}
}

// NewScriptRuntimeListParamsWithContext creates a new ScriptRuntimeListParams object
// with the default values initialized, and the ability to set a context for a request
func NewScriptRuntimeListParamsWithContext(ctx context.Context) *ScriptRuntimeListParams {
	var ()
	return &ScriptRuntimeListParams{

		Context: ctx,
	}
}

// NewScriptRuntimeListParamsWithHTTPClient creates a new ScriptRuntimeListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewScriptRuntimeListParamsWithHTTPClient(client *http.Client) *ScriptRuntimeListParams {
	var ()
	return &ScriptRuntimeListParams{
		HTTPClient: client,
	}
}

/*ScriptRuntimeListParams contains all the parameters to send to the API endpoint
for the script runtime list operation typically these are written to a http.Request
*/
type ScriptRuntimeListParams struct {

	/*Authorization*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the script runtime list params
func (o *ScriptRuntimeListParams) WithTimeout(timeout time.Duration) *ScriptRuntimeListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the script runtime list params
func (o *ScriptRuntimeListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the script runtime list params
func (o *ScriptRuntimeListParams) WithContext(ctx context.Context) *ScriptRuntimeListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the script runtime list params
func (o *ScriptRuntimeListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the script runtime list params
func (o *ScriptRuntimeListParams) WithHTTPClient(client *http.Client) *ScriptRuntimeListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the script runtime list params
func (o *ScriptRuntimeListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the script runtime list params
func (o *ScriptRuntimeListParams) WithAuthorization(authorization string) *ScriptRuntimeListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the script runtime list params
func (o *ScriptRuntimeListParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *ScriptRuntimeListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
