// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// ScriptDeleteReader is a Reader for the ScriptDelete structure.
type ScriptDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScriptDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewScriptDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewScriptDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewScriptDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewScriptDeleteOK creates a ScriptDeleteOK with default headers values
func NewScriptDeleteOK() *ScriptDeleteOK {
	return &ScriptDeleteOK{}
}

/*ScriptDeleteOK handles this case with default header values.

Ok
*/
type ScriptDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *ScriptDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /scripts/{id}][%d] scriptDeleteOK  %+v", 200, o.Payload)
}

func (o *ScriptDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScriptDeleteBadRequest creates a ScriptDeleteBadRequest with default headers values
func NewScriptDeleteBadRequest() *ScriptDeleteBadRequest {
	return &ScriptDeleteBadRequest{}
}

/*ScriptDeleteBadRequest handles this case with default header values.

Bad request
*/
type ScriptDeleteBadRequest struct {
}

func (o *ScriptDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scripts/{id}][%d] scriptDeleteBadRequest ", 400)
}

func (o *ScriptDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScriptDeleteDefault creates a ScriptDeleteDefault with default headers values
func NewScriptDeleteDefault(code int) *ScriptDeleteDefault {
	return &ScriptDeleteDefault{
		_statusCode: code,
	}
}

/*ScriptDeleteDefault handles this case with default header values.

Unexpected error
*/
type ScriptDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the script delete default response
func (o *ScriptDeleteDefault) Code() int {
	return o._statusCode
}

func (o *ScriptDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /scripts/{id}][%d] ScriptDelete default ", o._statusCode)
}

func (o *ScriptDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
