// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// SensorDeleteReader is a Reader for the SensorDelete structure.
type SensorDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SensorDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSensorDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSensorDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewSensorDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSensorDeleteOK creates a SensorDeleteOK with default headers values
func NewSensorDeleteOK() *SensorDeleteOK {
	return &SensorDeleteOK{}
}

/*SensorDeleteOK handles this case with default header values.

Ok
*/
type SensorDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *SensorDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /sensors/{id}][%d] sensorDeleteOK  %+v", 200, o.Payload)
}

func (o *SensorDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSensorDeleteBadRequest creates a SensorDeleteBadRequest with default headers values
func NewSensorDeleteBadRequest() *SensorDeleteBadRequest {
	return &SensorDeleteBadRequest{}
}

/*SensorDeleteBadRequest handles this case with default header values.

Bad request
*/
type SensorDeleteBadRequest struct {
}

func (o *SensorDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /sensors/{id}][%d] sensorDeleteBadRequest ", 400)
}

func (o *SensorDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSensorDeleteDefault creates a SensorDeleteDefault with default headers values
func NewSensorDeleteDefault(code int) *SensorDeleteDefault {
	return &SensorDeleteDefault{
		_statusCode: code,
	}
}

/*SensorDeleteDefault handles this case with default header values.

Unexpected error
*/
type SensorDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the sensor delete default response
func (o *SensorDeleteDefault) Code() int {
	return o._statusCode
}

func (o *SensorDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /sensors/{id}][%d] SensorDelete default ", o._statusCode)
}

func (o *SensorDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
