// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// SensorGetReader is a Reader for the SensorGet structure.
type SensorGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SensorGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSensorGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSensorGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewSensorGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSensorGetOK creates a SensorGetOK with default headers values
func NewSensorGetOK() *SensorGetOK {
	return &SensorGetOK{}
}

/*SensorGetOK handles this case with default header values.

Ok
*/
type SensorGetOK struct {
	Payload *models.Sensor
}

func (o *SensorGetOK) Error() string {
	return fmt.Sprintf("[GET /sensors/{id}][%d] sensorGetOK  %+v", 200, o.Payload)
}

func (o *SensorGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Sensor)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSensorGetBadRequest creates a SensorGetBadRequest with default headers values
func NewSensorGetBadRequest() *SensorGetBadRequest {
	return &SensorGetBadRequest{}
}

/*SensorGetBadRequest handles this case with default header values.

Bad request
*/
type SensorGetBadRequest struct {
}

func (o *SensorGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /sensors/{id}][%d] sensorGetBadRequest ", 400)
}

func (o *SensorGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSensorGetDefault creates a SensorGetDefault with default headers values
func NewSensorGetDefault(code int) *SensorGetDefault {
	return &SensorGetDefault{
		_statusCode: code,
	}
}

/*SensorGetDefault handles this case with default header values.

Unexpected error
*/
type SensorGetDefault struct {
	_statusCode int
}

// Code gets the status code for the sensor get default response
func (o *SensorGetDefault) Code() int {
	return o._statusCode
}

func (o *SensorGetDefault) Error() string {
	return fmt.Sprintf("[GET /sensors/{id}][%d] SensorGet default ", o._statusCode)
}

func (o *SensorGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
