// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// TenantPropsGetReader is a Reader for the TenantPropsGet structure.
type TenantPropsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantPropsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTenantPropsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewTenantPropsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewTenantPropsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTenantPropsGetOK creates a TenantPropsGetOK with default headers values
func NewTenantPropsGetOK() *TenantPropsGetOK {
	return &TenantPropsGetOK{}
}

/*TenantPropsGetOK handles this case with default header values.

Ok
*/
type TenantPropsGetOK struct {
	Payload *models.TenantProps
}

func (o *TenantPropsGetOK) Error() string {
	return fmt.Sprintf("[GET /tenantprops/{id}][%d] tenantPropsGetOK  %+v", 200, o.Payload)
}

func (o *TenantPropsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantProps)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTenantPropsGetBadRequest creates a TenantPropsGetBadRequest with default headers values
func NewTenantPropsGetBadRequest() *TenantPropsGetBadRequest {
	return &TenantPropsGetBadRequest{}
}

/*TenantPropsGetBadRequest handles this case with default header values.

Bad request
*/
type TenantPropsGetBadRequest struct {
}

func (o *TenantPropsGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /tenantprops/{id}][%d] tenantPropsGetBadRequest ", 400)
}

func (o *TenantPropsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTenantPropsGetDefault creates a TenantPropsGetDefault with default headers values
func NewTenantPropsGetDefault(code int) *TenantPropsGetDefault {
	return &TenantPropsGetDefault{
		_statusCode: code,
	}
}

/*TenantPropsGetDefault handles this case with default header values.

Unexpected error
*/
type TenantPropsGetDefault struct {
	_statusCode int
}

// Code gets the status code for the tenant props get default response
func (o *TenantPropsGetDefault) Code() int {
	return o._statusCode
}

func (o *TenantPropsGetDefault) Error() string {
	return fmt.Sprintf("[GET /tenantprops/{id}][%d] TenantPropsGet default ", o._statusCode)
}

func (o *TenantPropsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
