// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/doubret/terraform-provider-xiiot/models"
)

// UserPropsDeleteReader is a Reader for the UserPropsDelete structure.
type UserPropsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserPropsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserPropsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUserPropsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUserPropsDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUserPropsDeleteOK creates a UserPropsDeleteOK with default headers values
func NewUserPropsDeleteOK() *UserPropsDeleteOK {
	return &UserPropsDeleteOK{}
}

/*UserPropsDeleteOK handles this case with default header values.

Ok
*/
type UserPropsDeleteOK struct {
	Payload *models.DeleteDocumentResponse
}

func (o *UserPropsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /userprops/{id}][%d] userPropsDeleteOK  %+v", 200, o.Payload)
}

func (o *UserPropsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserPropsDeleteBadRequest creates a UserPropsDeleteBadRequest with default headers values
func NewUserPropsDeleteBadRequest() *UserPropsDeleteBadRequest {
	return &UserPropsDeleteBadRequest{}
}

/*UserPropsDeleteBadRequest handles this case with default header values.

Bad request
*/
type UserPropsDeleteBadRequest struct {
}

func (o *UserPropsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /userprops/{id}][%d] userPropsDeleteBadRequest ", 400)
}

func (o *UserPropsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUserPropsDeleteDefault creates a UserPropsDeleteDefault with default headers values
func NewUserPropsDeleteDefault(code int) *UserPropsDeleteDefault {
	return &UserPropsDeleteDefault{
		_statusCode: code,
	}
}

/*UserPropsDeleteDefault handles this case with default header values.

Unexpected error
*/
type UserPropsDeleteDefault struct {
	_statusCode int
}

// Code gets the status code for the user props delete default response
func (o *UserPropsDeleteDefault) Code() int {
	return o._statusCode
}

func (o *UserPropsDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /userprops/{id}][%d] UserPropsDelete default ", o._statusCode)
}

func (o *UserPropsDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
