// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EdgeUpgrade EdgeUpgrade is object model for EdgeUpgrade
// swagger:model EdgeUpgrade
type EdgeUpgrade struct {

	// The changes that were made in this release from the previous release
	// Required: true
	Changelog *string `json:"changelog"`

	// List of releases that can be upgraded to the new version
	// Required: true
	CompatibleReleases []string `json:"compatibleReleases"`

	// ID
	ID string `json:"id,omitempty"`

	// This is the release that is avaliable
	// Required: true
	Release *string `json:"release"`
}

// Validate validates this edge upgrade
func (m *EdgeUpgrade) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangelog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompatibleReleases(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelease(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EdgeUpgrade) validateChangelog(formats strfmt.Registry) error {

	if err := validate.Required("changelog", "body", m.Changelog); err != nil {
		return err
	}

	return nil
}

func (m *EdgeUpgrade) validateCompatibleReleases(formats strfmt.Registry) error {

	if err := validate.Required("compatibleReleases", "body", m.CompatibleReleases); err != nil {
		return err
	}

	return nil
}

func (m *EdgeUpgrade) validateRelease(formats strfmt.Registry) error {

	if err := validate.Required("release", "body", m.Release); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EdgeUpgrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EdgeUpgrade) UnmarshalBinary(b []byte) error {
	var res EdgeUpgrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
