// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// NotificationTopics notification topics
// swagger:model NotificationTopics
type NotificationTopics string

const (

	// NotificationTopicsReportEdge captures enum value "reportEdge"
	NotificationTopicsReportEdge NotificationTopics = "reportEdge"

	// NotificationTopicsOnDeleteEdge captures enum value "onDeleteEdge"
	NotificationTopicsOnDeleteEdge NotificationTopics = "onDeleteEdge"

	// NotificationTopicsOnUpdateEdge captures enum value "onUpdateEdge"
	NotificationTopicsOnUpdateEdge NotificationTopics = "onUpdateEdge"

	// NotificationTopicsReportSensors captures enum value "reportSensors"
	NotificationTopicsReportSensors NotificationTopics = "reportSensors"

	// NotificationTopicsReportEdgeInfo captures enum value "reportEdgeInfo"
	NotificationTopicsReportEdgeInfo NotificationTopics = "reportEdgeInfo"

	// NotificationTopicsApplicationStatus captures enum value "application-status"
	NotificationTopicsApplicationStatus NotificationTopics = "application-status"

	// NotificationTopicsOnCreateApplication captures enum value "onCreateApplication"
	NotificationTopicsOnCreateApplication NotificationTopics = "onCreateApplication"

	// NotificationTopicsOnDeleteApplication captures enum value "onDeleteApplication"
	NotificationTopicsOnDeleteApplication NotificationTopics = "onDeleteApplication"

	// NotificationTopicsOnUpdateApplication captures enum value "onUpdateApplication"
	NotificationTopicsOnUpdateApplication NotificationTopics = "onUpdateApplication"

	// NotificationTopicsOnCreateCategory captures enum value "onCreateCategory"
	NotificationTopicsOnCreateCategory NotificationTopics = "onCreateCategory"

	// NotificationTopicsOnDeleteCategory captures enum value "onDeleteCategory"
	NotificationTopicsOnDeleteCategory NotificationTopics = "onDeleteCategory"

	// NotificationTopicsOnUpdateCategory captures enum value "onUpdateCategory"
	NotificationTopicsOnUpdateCategory NotificationTopics = "onUpdateCategory"

	// NotificationTopicsOnCreateDataSource captures enum value "onCreateDataSource"
	NotificationTopicsOnCreateDataSource NotificationTopics = "onCreateDataSource"

	// NotificationTopicsOnDeleteDataSource captures enum value "onDeleteDataSource"
	NotificationTopicsOnDeleteDataSource NotificationTopics = "onDeleteDataSource"

	// NotificationTopicsOnUpdateDataSource captures enum value "onUpdateDataSource"
	NotificationTopicsOnUpdateDataSource NotificationTopics = "onUpdateDataSource"

	// NotificationTopicsOnCreateDockerProfile captures enum value "onCreateDockerProfile"
	NotificationTopicsOnCreateDockerProfile NotificationTopics = "onCreateDockerProfile"

	// NotificationTopicsOnDeleteDockerProfile captures enum value "onDeleteDockerProfile"
	NotificationTopicsOnDeleteDockerProfile NotificationTopics = "onDeleteDockerProfile"

	// NotificationTopicsOnUpdateDockerProfile captures enum value "onUpdateDockerProfile"
	NotificationTopicsOnUpdateDockerProfile NotificationTopics = "onUpdateDockerProfile"

	// NotificationTopicsOnCreateScript captures enum value "onCreateScript"
	NotificationTopicsOnCreateScript NotificationTopics = "onCreateScript"

	// NotificationTopicsOnDeleteScript captures enum value "onDeleteScript"
	NotificationTopicsOnDeleteScript NotificationTopics = "onDeleteScript"

	// NotificationTopicsOnUpdateScript captures enum value "onUpdateScript"
	NotificationTopicsOnUpdateScript NotificationTopics = "onUpdateScript"

	// NotificationTopicsOnCreateScriptRuntime captures enum value "onCreateScriptRuntime"
	NotificationTopicsOnCreateScriptRuntime NotificationTopics = "onCreateScriptRuntime"

	// NotificationTopicsOnDeleteScriptRuntime captures enum value "onDeleteScriptRuntime"
	NotificationTopicsOnDeleteScriptRuntime NotificationTopics = "onDeleteScriptRuntime"

	// NotificationTopicsOnUpdateScriptRuntime captures enum value "onUpdateScriptRuntime"
	NotificationTopicsOnUpdateScriptRuntime NotificationTopics = "onUpdateScriptRuntime"

	// NotificationTopicsOnCreateDataStream captures enum value "onCreateDataStream"
	NotificationTopicsOnCreateDataStream NotificationTopics = "onCreateDataStream"

	// NotificationTopicsOnDeleteDataStream captures enum value "onDeleteDataStream"
	NotificationTopicsOnDeleteDataStream NotificationTopics = "onDeleteDataStream"

	// NotificationTopicsOnUpdateDataStream captures enum value "onUpdateDataStream"
	NotificationTopicsOnUpdateDataStream NotificationTopics = "onUpdateDataStream"

	// NotificationTopicsOnCreateCloudCreds captures enum value "onCreateCloudCreds"
	NotificationTopicsOnCreateCloudCreds NotificationTopics = "onCreateCloudCreds"

	// NotificationTopicsOnDeleteCloudCreds captures enum value "onDeleteCloudCreds"
	NotificationTopicsOnDeleteCloudCreds NotificationTopics = "onDeleteCloudCreds"

	// NotificationTopicsOnUpdateCloudCreds captures enum value "onUpdateCloudCreds"
	NotificationTopicsOnUpdateCloudCreds NotificationTopics = "onUpdateCloudCreds"

	// NotificationTopicsOnCreateProject captures enum value "onCreateProject"
	NotificationTopicsOnCreateProject NotificationTopics = "onCreateProject"

	// NotificationTopicsOnDeleteProject captures enum value "onDeleteProject"
	NotificationTopicsOnDeleteProject NotificationTopics = "onDeleteProject"

	// NotificationTopicsOnUpdateProject captures enum value "onUpdateProject"
	NotificationTopicsOnUpdateProject NotificationTopics = "onUpdateProject"

	// NotificationTopicsLogUpload captures enum value "logUpload"
	NotificationTopicsLogUpload NotificationTopics = "logUpload"

	// NotificationTopicsLogUploadComplete captures enum value "logUploadComplete"
	NotificationTopicsLogUploadComplete NotificationTopics = "logUploadComplete"

	// NotificationTopicsExecuteEdgeUpgrade captures enum value "executeEdgeUpgrade"
	NotificationTopicsExecuteEdgeUpgrade NotificationTopics = "executeEdgeUpgrade"

	// NotificationTopicsSetupSSHTunneling captures enum value "setupSSHTunneling"
	NotificationTopicsSetupSSHTunneling NotificationTopics = "setupSSHTunneling"

	// NotificationTopicsTeardownSSHTunneling captures enum value "teardownSSHTunneling"
	NotificationTopicsTeardownSSHTunneling NotificationTopics = "teardownSSHTunneling"
)

// for schema
var notificationTopicsEnum []interface{}

func init() {
	var res []NotificationTopics
	if err := json.Unmarshal([]byte(`["reportEdge","onDeleteEdge","onUpdateEdge","reportSensors","reportEdgeInfo","application-status","onCreateApplication","onDeleteApplication","onUpdateApplication","onCreateCategory","onDeleteCategory","onUpdateCategory","onCreateDataSource","onDeleteDataSource","onUpdateDataSource","onCreateDockerProfile","onDeleteDockerProfile","onUpdateDockerProfile","onCreateScript","onDeleteScript","onUpdateScript","onCreateScriptRuntime","onDeleteScriptRuntime","onUpdateScriptRuntime","onCreateDataStream","onDeleteDataStream","onUpdateDataStream","onCreateCloudCreds","onDeleteCloudCreds","onUpdateCloudCreds","onCreateProject","onDeleteProject","onUpdateProject","logUpload","logUploadComplete","executeEdgeUpgrade","setupSSHTunneling","teardownSSHTunneling"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		notificationTopicsEnum = append(notificationTopicsEnum, v)
	}
}

func (m NotificationTopics) validateNotificationTopicsEnum(path, location string, value NotificationTopics) error {
	if err := validate.Enum(path, location, value, notificationTopicsEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this notification topics
func (m NotificationTopics) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateNotificationTopicsEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
