// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DataSourceFieldSelector DataSourceFieldSelector - data source field selector struct
//
// A DataSourceFieldSelector is a choice of a value from a category,
// together with a specification of scope on which fields
// this value applies to.
// User annotates each DataSource field with one or more
// CategoryInfo objects.
// Categories are the primary mechanism Sherlock provides
// user to specify the input of a DataStream.
// The list of categories spec is checked against each DataSource
// to determine whether any field in the DataSource should be
// included in the input of the DataStream.
// swagger:model DataSourceFieldSelector
type DataSourceFieldSelector struct {

	// The id of the category.
	// E.g., id for the Airport category
	// Required: true
	ID *string `json:"id"`

	// Name of the fields this CategoryInfo is applicable to.
	// The special value '\_\_ALL\_\_' means this CategoryInfo is applicable to
	// all fields in this DataSource.
	// Required: true
	Scope []string `json:"scope"`

	// The value chosen among allowed values from the category.
	// E.g., SFO
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this data source field selector
func (m *DataSourceFieldSelector) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataSourceFieldSelector) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *DataSourceFieldSelector) validateScope(formats strfmt.Registry) error {

	if err := validate.Required("scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

func (m *DataSourceFieldSelector) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataSourceFieldSelector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataSourceFieldSelector) UnmarshalBinary(b []byte) error {
	var res DataSourceFieldSelector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
