// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RequestLogUploadPayload Log upload request from the UI
// swagger:model RequestLogUploadPayload
type RequestLogUploadPayload struct {

	// application ID
	ApplicationID string `json:"applicationId,omitempty"`

	// edge ids
	// Required: true
	EdgeIds []string `json:"edgeIds"`
}

// Validate validates this request log upload payload
func (m *RequestLogUploadPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEdgeIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestLogUploadPayload) validateEdgeIds(formats strfmt.Registry) error {

	if err := validate.Required("edgeIds", "body", m.EdgeIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RequestLogUploadPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestLogUploadPayload) UnmarshalBinary(b []byte) error {
	var res RequestLogUploadPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
